Repository PaddlePaddle/PaddleNLP, pull requests merged in 2021-05, with the labels that each got.

#341 [STACL] Fix: overwrite nn.TransformerDecoder(for supporting paddle2.1)
  examples/machine_translation/text_simultaneous_translation/model.py
Labels: bugfix

#311 [Ready for Review] refine docs for xlnet modeling and tokenizer
  paddlenlp/transformers/xlnet/modeling.py
  paddlenlp/transformers/xlnet/tokenizer.py
Labels: documentation

#296 [WIP]Semantic index
  examples/semantic_indexing/README.md
  examples/semantic_indexing/ance/model.py
  examples/semantic_indexing/ann_util.py
  examples/semantic_indexing/base_model.py
  examples/semantic_indexing/batch_negative/model.py
  examples/semantic_indexing/data.py
  examples/semantic_indexing/evaluate.py
  examples/semantic_indexing/hardest_negative/model.py
  examples/semantic_indexing/predict.py
  examples/semantic_indexing/recall.py
  examples/semantic_indexing/run_ann_data_gen.py
  examples/semantic_indexing/train_ance.py
  examples/semantic_indexing/train_batch_neg.py
  examples/semantic_indexing/train_hardest_neg.py
Labels: enhancement

#325 Update some doc and add contribution doc
  docs/community/contribute_datasets/how_to_write_a_DatasetBuilder.rst
  docs/community/contribute_datasets/index.rst
  docs/community/contribute_datasets/sharing_dataset.rst
  docs/data_prepare/data_preprocess.rst
  docs/data_prepare/dataset_self_defined.rst
  docs/data_prepare/overview.rst
  docs/index.rst
  paddlenlp/datasets/dataset.py
Labels: documentation

#215 Enhance deploy for Transformer
  benchmark/transformer/README.md
  benchmark/transformer/configs/transformer.base.yaml
  benchmark/transformer/configs/transformer.big.yaml
  benchmark/transformer/dygraph/predict.py
  benchmark/transformer/dygraph/train.py
  benchmark/transformer/reader.py
  examples/machine_translation/transformer/README.md
  examples/machine_translation/transformer/configs/transformer.base.yaml
  examples/machine_translation/transformer/configs/transformer.big.yaml
  examples/machine_translation/transformer/deploy/cpp/CMakeLists.txt
  examples/machine_translation/transformer/deploy/cpp/README.md
  examples/machine_translation/transformer/deploy/cpp/helper.h
  examples/machine_translation/transformer/deploy/cpp/run.sh
  examples/machine_translation/transformer/deploy/cpp/run_impl.sh
  examples/machine_translation/transformer/deploy/cpp/transformer_e2e.cc
  examples/machine_translation/transformer/deploy/python/README.md
  examples/machine_translation/transformer/deploy/python/benchmark.sh
  examples/machine_translation/transformer/deploy/python/inference.py
  examples/machine_translation/transformer/deploy/python/utils/recorder.py
  examples/machine_translation/transformer/deploy/serving/README.md
  examples/machine_translation/transformer/deploy/serving/benchmark.py
  examples/machine_translation/transformer/deploy/serving/benchmark_serving.sh
  examples/machine_translation/transformer/deploy/serving/export_serving_model.py
  examples/machine_translation/transformer/deploy/serving/transformer_reader.py
  examples/machine_translation/transformer/deploy/serving/transformer_web_client.py
  examples/machine_translation/transformer/deploy/serving/transformer_web_server.py
  examples/machine_translation/transformer/deploy/serving/utils/recorder.py
  examples/machine_translation/transformer/faster_transformer/README.md
  examples/machine_translation/transformer/faster_transformer/encoder_decoding_predict.py
  examples/machine_translation/transformer/faster_transformer/export_model.py
  examples/machine_translation/transformer/predict.py
  examples/machine_translation/transformer/reader.py
  examples/machine_translation/transformer/static/predict.py
  examples/machine_translation/transformer/static/train.py
  examples/machine_translation/transformer/train.py
  examples/machine_translation/transformer/util/distributed_utils.py
  examples/machine_translation/transformer/util/record.py
  paddlenlp/ops/README.md
  paddlenlp/ops/sample/config/decoding.sample.yaml
  paddlenlp/ops/sample/decoding_sample.py
  paddlenlp/ops/sample/encoder_decoding_sample.py
Labels: enhancement

#354 [Docs] Add docs for distinct metric and unified_transformer.
  paddlenlp/data/collate.py
  paddlenlp/data/tokenizer.py
  paddlenlp/data/vocab.py
  paddlenlp/metrics/distinct.py
  paddlenlp/transformers/unified_transformer/modeling.py
  paddlenlp/transformers/unified_transformer/tokenizer.py
Labels: documentation

#371 [Bug] Fixed bugs of generation api and unified_transformer model.
  paddlenlp/transformers/generation_utils.py
  paddlenlp/transformers/unified_transformer/modeling.py
Labels: bugfix

#376 add doc string for squad metric
  docs/source/paddlenlp.metrics.rst
  paddlenlp/metrics/squad.py
Labels: documentation

#287 refine seq2vec/ERNIE doc_string
  paddlenlp/seq2vec/encoder.py
  paddlenlp/transformers/ernie/modeling.py
  paddlenlp/transformers/ernie/tokenizer.py
Labels: documentation

#267 Pre-trained data preprocess
  examples/language_model/pretraining_data_prepare/README.md
  examples/language_model/pretraining_data_prepare/create_pretraining_data.py
  examples/language_model/pretraining_data_prepare/main.py
  examples/language_model/pretraining_data_prepare/requirements.txt
  examples/language_model/pretraining_data_prepare/text_formatting/bookcorpus.py
  examples/language_model/pretraining_data_prepare/text_formatting/wikicorpus.py
  examples/language_model/pretraining_data_prepare/text_sharding.py
Labels: enhancement

#382 Enable viterbi to static model
  examples/lexical_analysis/README.md
  examples/lexical_analysis/deploy/predict.py
  examples/lexical_analysis/export_model.py
  paddlenlp/layers/crf.py
Labels: bugfix

#304 [Ready for Review] add albert model
  docs/model_zoo.md
  docs/transformers.md
  examples/benchmark/glue/run_glue.py
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/albert/__init__.py
  paddlenlp/transformers/albert/modeling.py
  paddlenlp/transformers/albert/tokenizer.py
Labels: enhancement

#323 [WIP] [ERNIE] Add ernie hybrid parallelism.
  examples/language_model/ernie/README.md
  examples/language_model/ernie/config/ernie_174b_config_proj.json
  examples/language_model/ernie/config/ernie_230b_config_proj.json
  examples/language_model/ernie/config/ernie_base_config.json
  examples/language_model/ernie/model/__init__.py
  examples/language_model/ernie/model/ernie.py
  examples/language_model/ernie/model/transformer_encoder.py
  examples/language_model/ernie/pretrain.sh
  examples/language_model/ernie/pretraining_args.py
  examples/language_model/ernie/propeller/__init__.py
  examples/language_model/ernie/propeller/data/__init__.py
  examples/language_model/ernie/propeller/data/example.proto
  examples/language_model/ernie/propeller/data/example_pb2.py
  examples/language_model/ernie/propeller/data/feature.proto
  examples/language_model/ernie/propeller/data/feature_column.py
  examples/language_model/ernie/propeller/data/feature_pb2.py
  examples/language_model/ernie/propeller/data/functional.py
  examples/language_model/ernie/propeller/types.py
  examples/language_model/ernie/propeller/util.py
  examples/language_model/ernie/reader/__init__.py
  examples/language_model/ernie/reader/pretraining_ds_ernie_full_sent.py
  examples/language_model/ernie/reader/pretraining_ds_mlm.py
  examples/language_model/ernie/run_pretraining.py
  examples/language_model/ernie/utils/__init__.py
  examples/language_model/ernie/utils/args.py
  examples/language_model/ernie/utils/init.py
  examples/language_model/ernie/utils/random.py
  examples/language_model/ernie/utils/topo.py
  examples/language_model/gpt/run_pretrain_static.py
  paddlenlp/ops/optimizer/AdamwOptimizer.py
  paddlenlp/ops/optimizer/__init__.py
  paddlenlp/ops/optimizer/adamw.cc
  paddlenlp/ops/optimizer/adamw.cu
  paddlenlp/ops/optimizer/adamw.py
Labels: enhancement

#291 optimize crf, tcn and erniectm docstring
  paddlenlp/layers/crf.py
  paddlenlp/layers/sequence.py
  paddlenlp/layers/tcn.py
  paddlenlp/transformers/ernie/modeling.py
  paddlenlp/transformers/ernie_ctm/modeling.py
  paddlenlp/transformers/ernie_ctm/tokenizer.py
Labels: documentation

#380 Add P-tuning for few_shot
  examples/few_shot/README.md
  examples/few_shot/p-tuning/README.md
  examples/few_shot/p-tuning/data.py
  examples/few_shot/p-tuning/evaluate.py
  examples/few_shot/p-tuning/imgs/ptuning.png
  examples/few_shot/p-tuning/label_normalized/bustm.json
  examples/few_shot/p-tuning/label_normalized/chid.json
  examples/few_shot/p-tuning/label_normalized/cluewsc.json
  examples/few_shot/p-tuning/label_normalized/csl.json
  examples/few_shot/p-tuning/label_normalized/csldcp.json
  examples/few_shot/p-tuning/label_normalized/eprstmt.json
  examples/few_shot/p-tuning/label_normalized/iflytek.json
  examples/few_shot/p-tuning/label_normalized/ocnli.json
  examples/few_shot/p-tuning/label_normalized/tnews.json
  examples/few_shot/p-tuning/model.py
  examples/few_shot/p-tuning/ptuning.py
  paddlenlp/datasets/fewclue.py
Labels: enhancement

#435 GPT Fix Tensor Parallelism and DistributedBatchSampler
  examples/language_model/gpt/dataset.py
  examples/language_model/gpt/run_pretrain.py
  examples/language_model/gpt/run_pretrain_static.py
  paddlenlp/ops/distributed/parallel.py
  paddlenlp/ops/distributed/utils/topo.py
  paddlenlp/transformers/gpt/modeling.py
Labels: bugfix

#464 fix 2.0.1 crf bug
  examples/information_extraction/waybill_ie/run_bigru_crf.py
  examples/information_extraction/waybill_ie/run_ernie.py
  examples/information_extraction/waybill_ie/run_ernie_crf.py
Labels: bugfix
