Repository PaddlePaddle/PaddleNLP, pull requests merged in 2021-06, with the labels that each got.

#289 [WIP] Update api docs for PretrainedModel and PretrainedTokenizer
  docs/source/paddlenlp.transformers.tokenizer_utils.rst
  paddlenlp/transformers/bert/modeling.py
  paddlenlp/transformers/model_utils.py
  paddlenlp/transformers/tokenizer_utils.py
Labels: documentation

#467 Add NeZha Language Model
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/nezha/__init__.py
  paddlenlp/transformers/nezha/modeling.py
  paddlenlp/transformers/nezha/tokenizer.py
Labels: enhancement

#313 Add tiny bert model
  docs/transformers.md
  examples/model_compression/distill_lstm/README.md
  examples/model_compression/tinybert/README.md
  examples/model_compression/tinybert/data_augmentation.py
  examples/model_compression/tinybert/task_distill.py
  paddlenlp/datasets/clue.py
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/distill_utils.py
  paddlenlp/transformers/tinybert/__init__.py
  paddlenlp/transformers/tinybert/modeling.py
  paddlenlp/transformers/tinybert/tokenizer.py
Labels: enhancement

#478 modify transformers.md
  README.md
  docs/index.rst
  docs/model_zoo/transformers.md
  docs/model_zoo/transformers.rst
  docs/models.md
  docs/transformers.md
Labels: documentation

#496 modify transformers.rst
  docs/model_zoo/transformers.rst
Labels: documentation

#504 Update english readme
  README_en.md
Labels: documentation

#500 NLPCC14-SC Support！
  paddlenlp/datasets/__init__.py
  paddlenlp/datasets/nlpcc14_sc.py
Labels: SIG, data

#523 Update docs and readme
  README.md
  README_en.md
Labels: documentation

#553 optimization for read_func of `lcqmc`
  paddlenlp/datasets/lcqmc.py
Labels: data

#550 fix ofa demo in distribute
  examples/model_compression/ofa/run_glue_ofa.py
Labels: bugfix

#559 Add PAWS-X Dataset
  paddlenlp/datasets/paws-x.py
Labels: SIG, data

#562 Add BQCorpus Dataset
  paddlenlp/datasets/bq_corpus.py
Labels: SIG, data

#592 Add SE-ABSA16_CAME Dataset
  paddlenlp/datasets/seabsa16.py
Labels: SIG, data

#499 add text cls serving deployed scripts
  examples/text_classification/pretrained_models/README.md
  examples/text_classification/pretrained_models/deploy/serving/client.py
  examples/text_classification/pretrained_models/deploy/serving/export_servable_model.py
Labels: deploy

#593 Add COTE-BD & COTE-MFW Dataset
  paddlenlp/datasets/cote.py
Labels: SIG, data

#608 batch bug fix of decoder_weight shape in transformers' model
  paddlenlp/transformers/bert/modeling.py
  paddlenlp/transformers/bigbird/modeling.py
  paddlenlp/transformers/ernie/modeling.py
  paddlenlp/transformers/gpt/modeling.py
  paddlenlp/transformers/unified_transformer/modeling.py
Labels: bugfix

#655 Fix cuda memory leak
  paddlenlp/ops/faster_transformer/src/fusion_decoding_op.cu
  paddlenlp/ops/faster_transformer/src/fusion_gpt_op.cu
Labels: bugfix
