Repository PaddlePaddle/PaddleNLP, pull requests merged in 2021-07, with the labels that each got.

#674 [TextCNN] Add TextCNN example for sentiment analysis
  examples/sentiment_analysis/textcnn/README.md
  examples/sentiment_analysis/textcnn/data.py
  examples/sentiment_analysis/textcnn/deploy/python/predict.py
  examples/sentiment_analysis/textcnn/export_model.py
  examples/sentiment_analysis/textcnn/model.py
  examples/sentiment_analysis/textcnn/predict.py
  examples/sentiment_analysis/textcnn/train.py
Labels: enhancement

#712 Add hyp thunews
  docs/data_prepare/dataset_list.md
  paddlenlp/datasets/__init__.py
  paddlenlp/datasets/hyp.py
  paddlenlp/datasets/thucnews.py
Labels: data

#706 Add SimBERT for text matching
  docs/model_zoo/transformers.rst
  examples/text_matching/simbert/README.md
  examples/text_matching/simbert/data.py
  examples/text_matching/simbert/predict.py
  paddlenlp/transformers/bert/modeling.py
  paddlenlp/transformers/bert/tokenizer.py
Labels: enhancement

#746 Del self in GenerationMixin.
  paddlenlp/transformers/generation_utils.py
Labels: bugfix

#749 Fix the bug when batch size of crf input equal to 1.
  paddlenlp/layers/crf.py
Labels: bugfix

#754 Add C3, TriviaQa, CAIL2019-SCM dataset
  docs/data_prepare/dataset_list.md
  paddlenlp/datasets/c3.py
  paddlenlp/datasets/cail2019_scm.py
  paddlenlp/datasets/triviaqa.py
Labels: data

#663 [Feat] Add BART model
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/bart/__init__.py
  paddlenlp/transformers/bart/modeling.py
  paddlenlp/transformers/bart/tokenizer.py
Labels: enhancement

#807 Simplify visualdl dependency
  examples/word_embedding/README.md
Labels: installation

#802 Add PET for few_shot
  examples/few_shot/README.md
  examples/few_shot/pet/README.md
  examples/few_shot/pet/data.py
  examples/few_shot/pet/evaluate.py
  examples/few_shot/pet/label_normalized/bustm.json
  examples/few_shot/pet/label_normalized/chid.json
  examples/few_shot/pet/label_normalized/cluewsc.json
  examples/few_shot/pet/label_normalized/csl.json
  examples/few_shot/pet/label_normalized/csldcp.json
  examples/few_shot/pet/label_normalized/eprstmt.json
  examples/few_shot/pet/label_normalized/iflytek.json
  examples/few_shot/pet/label_normalized/ocnli.json
  examples/few_shot/pet/label_normalized/tnews.json
  examples/few_shot/pet/model.py
  examples/few_shot/pet/pet.py
  examples/few_shot/pet/predict.py
Labels: enhancement
