Repository PaddlePaddle/PaddleNLP, pull requests merged in 2022-06, with the labels that each got.

#1845 【Hackathon No.77】基于ERNIE_DOC完成长文本分类任务
  examples/text_classification/ernie_doc/README.md
  examples/text_classification/ernie_doc/__init__.py
  examples/text_classification/ernie_doc/data.py
  examples/text_classification/ernie_doc/export_model.py
  examples/text_classification/ernie_doc/metrics.py
  examples/text_classification/ernie_doc/modeling.py
  examples/text_classification/ernie_doc/predict.py
  examples/text_classification/ernie_doc/train.py
Labels: contributions

#2479 [BugFix] Fix load ckpt weight for amp 02
  model_zoo/ernie-1.0/run_pretrain.py
Labels: bug

#2080 [NEW MODEL] Add_XLM_model
  examples/language_model/xlm/README.md
  examples/language_model/xlm/framework.jpg
  examples/language_model/xlm/xnli_eval.py
  examples/language_model/xlm/xnli_train.py
  model_zoo/ernie-3.0/deploy/triton/models/ernie_tokencls_postprocess/1/model.py
  model_zoo/ernie-3.0/deploy/triton/token_cls_grpc_client.py
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/auto/modeling.py
  paddlenlp/transformers/auto/tokenizer.py
  paddlenlp/transformers/tokenizer_utils.py
  paddlenlp/transformers/xlm/__init__.py
  paddlenlp/transformers/xlm/modeling.py
  paddlenlp/transformers/xlm/tokenizer.py
Labels: contributions

#2519 [FasterBART] Suppport dygraph to static and inference
  paddlenlp/ops/faster_transformer/sample/bart_decoding_sample.py
  paddlenlp/ops/faster_transformer/sample/bart_export_model_sample.py
  paddlenlp/ops/faster_transformer/sample/bart_inference.py
  paddlenlp/ops/faster_transformer/transformer/decoding.py
  paddlenlp/ops/faster_transformer/transformer/faster_transformer.py
  paddlenlp/transformers/bart/modeling.py
Labels: faster

#2540 Add the WordTag-IE tool
  docs/model_zoo/taskflow.md
  examples/text_to_knowledge/README.md
  examples/text_to_knowledge/wordtag-ie/README.md
  examples/text_to_knowledge/wordtag-ie/demo_config.json
  examples/text_to_knowledge/wordtag/README.md
  paddlenlp/taskflow/knowledge_mining.py
  paddlenlp/taskflow/named_entity_recognition.py
  paddlenlp/taskflow/taskflow.py
  paddlenlp/taskflow/utils.py
Labels: enhancement

#2423 add resize_token_embeddings to Class PretrainedModel
  paddlenlp/transformers/model_utils.py
Labels: enhancement

#2576 Use AdamW with lr_ratio setting instead of AdamWDL
  examples/text_classification/ernie_doc/README.md
  examples/text_classification/ernie_doc/train.py
  model_zoo/ernie-doc/run_classifier.py
  model_zoo/ernie-doc/run_mcq.py
  model_zoo/ernie-doc/run_mrc.py
  model_zoo/ernie-doc/run_semantic_matching.py
  model_zoo/ernie-doc/run_sequence_labeling.py
  model_zoo/ernie-m/run_classifier.py
  paddlenlp/ops/optimizer/__init__.py
  paddlenlp/ops/optimizer/adamwdl.py
Labels: enhancement

#2558 fix evaluation for the case of overlapping in the same category
  paddlenlp/metrics/span.py
Labels: bugfix

#2626 Support evaluation for each class separately
  model_zoo/uie/README.md
  model_zoo/uie/deploy/python/infer_cpu.py
  model_zoo/uie/deploy/python/infer_gpu.py
  model_zoo/uie/deploy/python/uie_predictor.py
  model_zoo/uie/doccano.md
  model_zoo/uie/doccano.py
  model_zoo/uie/evaluate.py
  model_zoo/uie/utils.py
  paddlenlp/taskflow/information_extraction.py
Labels: enhancement

#2501 add hierarchical text classification
  applications/text_classification/hierarchical_classification/README.md
  applications/text_classification/hierarchical_classification/deploy/paddle_serving/README.md
  applications/text_classification/hierarchical_classification/deploy/paddle_serving/config.yml
  applications/text_classification/hierarchical_classification/deploy/paddle_serving/rpc_client.py
  applications/text_classification/hierarchical_classification/deploy/paddle_serving/service.py
  applications/text_classification/hierarchical_classification/deploy/predictor/README.md
  applications/text_classification/hierarchical_classification/deploy/predictor/infer.py
  applications/text_classification/hierarchical_classification/deploy/predictor/predictor.py
  applications/text_classification/hierarchical_classification/deploy/triton_serving/README.md
  applications/text_classification/hierarchical_classification/deploy/triton_serving/models/seqcls/config.pbtxt
  applications/text_classification/hierarchical_classification/deploy/triton_serving/models/seqcls_model/config.pbtxt
  applications/text_classification/hierarchical_classification/deploy/triton_serving/models/seqcls_postprocess/1/model.py
  applications/text_classification/hierarchical_classification/deploy/triton_serving/models/seqcls_postprocess/config.pbtxt
  applications/text_classification/hierarchical_classification/deploy/triton_serving/models/tokenizer/1/model.py
  applications/text_classification/hierarchical_classification/deploy/triton_serving/models/tokenizer/config.pbtxt
  applications/text_classification/hierarchical_classification/deploy/triton_serving/seqcls_grpc_client.py
  applications/text_classification/hierarchical_classification/export_model.py
  applications/text_classification/hierarchical_classification/metric.py
  applications/text_classification/hierarchical_classification/predict.py
  applications/text_classification/hierarchical_classification/prune.py
  applications/text_classification/hierarchical_classification/prune_config.json
  applications/text_classification/hierarchical_classification/prune_trainer.py
  applications/text_classification/hierarchical_classification/requirements.txt
  applications/text_classification/hierarchical_classification/train.py
  applications/text_classification/hierarchical_classification/utils.py
  paddlenlp/datasets/wos.py
Labels: enhancement

#2604 Add uie-mini, uie-micro and uie-nano for UIE
  docs/model_zoo/taskflow.md
  model_zoo/uie/README.md
  model_zoo/uie/finetune.py
  model_zoo/uie/utils.py
  paddlenlp/taskflow/information_extraction.py
  paddlenlp/taskflow/taskflow.py
Labels: enhancement

#2594 Optimize ERNIE Tiny 3.0 README
  docs/model_zoo/transformers/ERNIE/contents.rst
  examples/benchmark/clue/README.md
  examples/benchmark/clue/grid_search_tools/draw_pic.py
  examples/benchmark/clue/grid_search_tools/extract_result.sh
  examples/benchmark/clue/grid_search_tools/run_cls.sh
  examples/benchmark/clue/grid_search_tools/run_mrc.sh
  model_zoo/ernie-3.0/README.md
Labels: documentation

#2671 add export infer model function for PET
  examples/few_shot/pet/export_model.py
Labels: deploy

#2661 add multi label classification application
  applications/text_classification/hierarchical/README.md
  applications/text_classification/hierarchical/deploy/paddle_serving/README.md
  applications/text_classification/hierarchical/deploy/paddle_serving/config.yml
  applications/text_classification/hierarchical/deploy/paddle_serving/rpc_client.py
  applications/text_classification/hierarchical/deploy/paddle_serving/service.py
  applications/text_classification/hierarchical/deploy/predictor/README.md
  applications/text_classification/hierarchical/deploy/predictor/infer.py
  applications/text_classification/hierarchical/deploy/predictor/predictor.py
  applications/text_classification/hierarchical/deploy/triton_serving/README.md
  applications/text_classification/hierarchical/deploy/triton_serving/models/seqcls/config.pbtxt
  applications/text_classification/hierarchical/deploy/triton_serving/models/seqcls_model/config.pbtxt
  applications/text_classification/hierarchical/deploy/triton_serving/models/seqcls_postprocess/1/model.py
  applications/text_classification/hierarchical/deploy/triton_serving/models/seqcls_postprocess/config.pbtxt
  applications/text_classification/hierarchical/deploy/triton_serving/models/tokenizer/1/model.py
  applications/text_classification/hierarchical/deploy/triton_serving/models/tokenizer/config.pbtxt
  applications/text_classification/hierarchical/deploy/triton_serving/seqcls_grpc_client.py
  applications/text_classification/hierarchical/export_model.py
  applications/text_classification/hierarchical/metric.py
  applications/text_classification/hierarchical/predict.py
  applications/text_classification/hierarchical/prune.py
  applications/text_classification/hierarchical/prune_config.json
  applications/text_classification/hierarchical/prune_trainer.py
  applications/text_classification/hierarchical/requirements.txt
  applications/text_classification/hierarchical/train.py
  applications/text_classification/hierarchical/utils.py
  applications/text_classification/multi_label/README.md
  applications/text_classification/multi_label/deploy/paddle_serving/README.md
  applications/text_classification/multi_label/deploy/paddle_serving/config.yml
  applications/text_classification/multi_label/deploy/paddle_serving/rpc_client.py
  applications/text_classification/multi_label/deploy/paddle_serving/service.py
  applications/text_classification/multi_label/deploy/predictor/README.md
  applications/text_classification/multi_label/deploy/predictor/infer.py
  applications/text_classification/multi_label/deploy/predictor/predictor.py
  applications/text_classification/multi_label/deploy/triton_serving/README.md
  applications/text_classification/multi_label/deploy/triton_serving/models/seqcls/config.pbtxt
  applications/text_classification/multi_label/deploy/triton_serving/models/seqcls_model/config.pbtxt
  applications/text_classification/multi_label/deploy/triton_serving/models/seqcls_postprocess/1/model.py
  applications/text_classification/multi_label/deploy/triton_serving/models/seqcls_postprocess/config.pbtxt
  applications/text_classification/multi_label/deploy/triton_serving/models/tokenizer/1/model.py
  applications/text_classification/multi_label/deploy/triton_serving/models/tokenizer/config.pbtxt
  applications/text_classification/multi_label/deploy/triton_serving/seqcls_grpc_client.py
  applications/text_classification/multi_label/export_model.py
  applications/text_classification/multi_label/metric.py
  applications/text_classification/multi_label/predict.py
  applications/text_classification/multi_label/prune.py
  applications/text_classification/multi_label/prune_config.json
  applications/text_classification/multi_label/prune_trainer.py
  applications/text_classification/multi_label/requirements.txt
  applications/text_classification/multi_label/train.py
  applications/text_classification/multi_label/utils.py
Labels: enhancement, text classification

#2679 Update README.md for UIE
  docs/model_zoo/taskflow.md
  model_zoo/uie/README.md
Labels: documentation

#2692 update the document for the pet
  examples/few_shot/pet/README.md
Labels: few-shot
