Repository PaddlePaddle/PaddleNLP, pull requests merged in 2022-03, with the labels that each got.

#1559 FT support context forward acceleration
  paddlenlp/ops/CMakeLists.txt
  paddlenlp/ops/faster_transformer/src/fusion_unified_decoding_op.cc
  paddlenlp/ops/faster_transformer/src/fusion_unified_decoding_op.cu
  paddlenlp/ops/faster_transformer/src/fusion_unified_decoding_op.h
  paddlenlp/ops/faster_transformer/transformer/decoding.py
  paddlenlp/ops/faster_transformer/transformer/faster_transformer.py
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/cuda/cuda_kernels.h
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/cuda/decoding_kernels.cu
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/cuda/open_decoder.cu
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/cuda/open_decoder.cuh
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/cuda/topk_kernels.cu
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/cuda/topk_kernels.cuh
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/cuda/transformer_cuda_kernels.h
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/cuda/transformer_decoding_kernels.cu
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/decoding_beamsearch.h
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/decoding_sampling.h
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/open_decoder.h
  paddlenlp/ops/patches/FasterTransformer/fastertransformer/utils/arguments.h
  paddlenlp/transformers/bart/modeling.py
  paddlenlp/transformers/generation_utils.py
  paddlenlp/transformers/gpt/modeling.py
  paddlenlp/transformers/mbart/modeling.py
Labels: faster

#1698 Add model Prohetnet
  examples/text_summarization/prophetnet/README.md
  examples/text_summarization/prophetnet/eval.py
  examples/text_summarization/prophetnet/evaluate/cnndm/bs_pyrouge.py
  examples/text_summarization/prophetnet/evaluate/cnndm/postprocess_cnn_dm.py
  examples/text_summarization/prophetnet/evaluate/gigaword/bs_pyrouge.py
  examples/text_summarization/prophetnet/evaluate/gigaword/eval.py
  examples/text_summarization/prophetnet/generate.py
  examples/text_summarization/prophetnet/requirements.txt
  examples/text_summarization/prophetnet/run_eval.sh
  examples/text_summarization/prophetnet/run_train.sh
  examples/text_summarization/prophetnet/train_prophetnet.py
  examples/text_summarization/prophetnet/uncase_tokenize_data.py
  examples/text_summarization/prophetnet/uncompress_data.sh
  paddlenlp/transformers/prophetnet/__init__.py
  paddlenlp/transformers/prophetnet/modeling.py
  paddlenlp/transformers/prophetnet/tokenizer.py
Labels: contributions

#1677 Add model LUKE
  examples/language_model/luke/README.md
  examples/language_model/luke/args.py
  examples/language_model/luke/open_entity_processor.py
  examples/language_model/luke/run_open_entity.py
  examples/language_model/luke/run_squad.py
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/luke/__init__.py
  paddlenlp/transformers/luke/modeling.py
  paddlenlp/transformers/luke/tokenizer.py
Labels: contributions

#1678 Add model MegatronBert
  examples/language_model/megatronbert/README.md
  examples/language_model/megatronbert/args.py
  examples/language_model/megatronbert/run_glue.py
  examples/language_model/megatronbert/run_squad.py
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/megatronbert/__init__.py
  paddlenlp/transformers/megatronbert/modeling.py
  paddlenlp/transformers/megatronbert/tokenizer.py
Labels: contributions

#1770 [BUGFIX] Rename ernie-gen model name
  paddlenlp/transformers/ernie_gen/modeling.py
Labels: bugfix

#1681 [BUGFIX] fix hang when training and evaluation in multi-gpus model
  examples/language_model/ernie-m/run_classifier.py
Labels: bugfix
