Repository PaddlePaddle/PaddleNLP, pull requests merged in 2022-07, with the labels that each got.

#2690 add infer predict function for PET
  examples/few_shot/pet/deploy/python/README.md
  examples/few_shot/pet/deploy/python/predict.py
Labels: few-shot

#2710 Fix droput prediction bug and Add faq for milvus indexing of neural search
  applications/neural_search/recall/milvus/README.md
  applications/neural_search/recall/milvus/embedding_insert.py
  applications/neural_search/recall/milvus/inference.py
  applications/neural_search/recall/milvus/milvus_recall.py
Labels: documentation, pipelines

#2709 Add faiss dependancy and Add utf-8 faq hint of pipelines
  applications/experimental/pipelines/examples/question-answering/README.md
  applications/experimental/pipelines/requirements.txt
Labels: documentation, pipelines

#2675 add multi classification application
  applications/text_classification/doccano.md
  applications/text_classification/doccano.py
  applications/text_classification/multi_class/README.md
  applications/text_classification/multi_class/deploy/paddle_serving/README.md
  applications/text_classification/multi_class/deploy/paddle_serving/config.yml
  applications/text_classification/multi_class/deploy/paddle_serving/rpc_client.py
  applications/text_classification/multi_class/deploy/paddle_serving/service.py
  applications/text_classification/multi_class/deploy/predictor/README.md
  applications/text_classification/multi_class/deploy/predictor/infer.py
  applications/text_classification/multi_class/deploy/predictor/predictor.py
  applications/text_classification/multi_class/deploy/triton_serving/README.md
  applications/text_classification/multi_class/deploy/triton_serving/models/seqcls/config.pbtxt
  applications/text_classification/multi_class/deploy/triton_serving/models/seqcls_model/config.pbtxt
  applications/text_classification/multi_class/deploy/triton_serving/models/seqcls_postprocess/1/model.py
  applications/text_classification/multi_class/deploy/triton_serving/models/seqcls_postprocess/config.pbtxt
  applications/text_classification/multi_class/deploy/triton_serving/models/tokenizer/1/model.py
  applications/text_classification/multi_class/deploy/triton_serving/models/tokenizer/config.pbtxt
  applications/text_classification/multi_class/deploy/triton_serving/seqcls_grpc_client.py
  applications/text_classification/multi_class/export_model.py
  applications/text_classification/multi_class/predict.py
  applications/text_classification/multi_class/prune.py
  applications/text_classification/multi_class/prune_config.json
  applications/text_classification/multi_class/prune_trainer.py
  applications/text_classification/multi_class/train.py
  applications/text_classification/multi_class/utils.py
Labels: enhancement, text classification

#2707 fix bug of file updating
  model_zoo/uie/README.md
  paddlenlp/taskflow/text_generation.py
Labels: bugfix

#2719 Update some fluid api usage and fix a typo.
  model_zoo/ernie-1.0/run_pretrain.py
  paddlenlp/experimental/faster_tokenizer.py
  paddlenlp/layers/crf.py
Labels: bugfix

#2684 [TRAINER] Optimize logs for benchmark.
  paddlenlp/trainer/trainer_callback.py
Labels: pre-training

#2734 Update README_en.md
  README_en.md
Labels: documentation

#2735 Fix Electra inference
  model_zoo/electra/deploy/python/predict.py
Labels: bugfix

#2736 Fix the max_seq_len bug of pipelines for semantic search
  applications/experimental/pipelines/pipelines/data_handler/processor.py
Labels: bugfix, pipelines

#2721 Add c++ and pipeline Paddle Serving Support of ranking model for neural search
  applications/neural_search/ranking/ernie_matching/README.md
  applications/neural_search/ranking/ernie_matching/deploy/cpp/http_client.py
  applications/neural_search/ranking/ernie_matching/deploy/cpp/rpc_client.py
  applications/neural_search/ranking/ernie_matching/deploy/cpp/start_server.sh
  applications/neural_search/ranking/ernie_matching/deploy/python/config_nlp.yml
  applications/neural_search/ranking/ernie_matching/deploy/python/predict.py
  applications/neural_search/ranking/ernie_matching/deploy/python/rpc_client.py
  applications/neural_search/ranking/ernie_matching/deploy/python/web_service.py
  applications/neural_search/ranking/ernie_matching/export_to_serving.py
  applications/neural_search/ranking/ernie_matching/model.py
  applications/neural_search/ranking/ernie_matching/predict_pairwise.py
  applications/neural_search/ranking/ernie_matching/scripts/export_to_serving.sh
  applications/neural_search/ranking/ernie_matching/scripts/train_pairwise.sh
  applications/neural_search/ranking/ernie_matching/train_pairwise.py
  applications/neural_search/recall/milvus/feature_extract.py
  applications/neural_search/recall/milvus/scripts/feature_extract.sh
  applications/neural_search/requirements.txt
  applications/neural_search/search_system/README.md
  applications/neural_search/search_system/config.py
  applications/neural_search/search_system/data.py
  applications/neural_search/search_system/milvus_util.py
  applications/neural_search/search_system/run_system.py
Labels: deploy, pipelines

#2745 [Bug fixes] setting max_position_embeddings in roformer model
  paddlenlp/transformers/roformer/modeling.py
Labels: bugfix

#2752 Fix import error
  applications/neural_search/README.md
  examples/information_extraction/waybill_ie/run_ernie_crf.py
  examples/text_matching/question_matching/train.py
Labels: bugfix

#2727 optimize text classification
  applications/text_classification/README.md
  applications/text_classification/doccano.md
  applications/text_classification/doccano.py
  applications/text_classification/hierarchical/README.md
  applications/text_classification/hierarchical/deploy/paddle_serving/README.md
  applications/text_classification/hierarchical/deploy/paddle_serving/config.yml
  applications/text_classification/hierarchical/deploy/predictor/README.md
  applications/text_classification/hierarchical/deploy/predictor/infer.py
  applications/text_classification/hierarchical/deploy/predictor/predictor.py
  applications/text_classification/hierarchical/deploy/triton_serving/README.md
  applications/text_classification/hierarchical/export_model.py
  applications/text_classification/hierarchical/predict.py
  applications/text_classification/hierarchical/prune.py
  applications/text_classification/hierarchical/train.py
  applications/text_classification/hierarchical/utils.py
  applications/text_classification/multi_class/README.md
  applications/text_classification/multi_class/deploy/paddle_serving/README.md
  applications/text_classification/multi_class/deploy/paddle_serving/config.yml
  applications/text_classification/multi_class/deploy/predictor/README.md
  applications/text_classification/multi_class/deploy/triton_serving/README.md
  applications/text_classification/multi_class/export_model.py
  applications/text_classification/multi_class/predict.py
  applications/text_classification/multi_class/prune.py
  applications/text_classification/multi_class/train.py
  applications/text_classification/multi_class/utils.py
  applications/text_classification/multi_label/README.md
  applications/text_classification/multi_label/deploy/paddle_serving/README.md
  applications/text_classification/multi_label/deploy/paddle_serving/config.yml
  applications/text_classification/multi_label/deploy/predictor/README.md
  applications/text_classification/multi_label/deploy/predictor/predictor.py
  applications/text_classification/multi_label/deploy/triton_serving/README.md
  applications/text_classification/multi_label/export_model.py
  applications/text_classification/multi_label/predict.py
  applications/text_classification/multi_label/prune.py
  applications/text_classification/multi_label/train.py
  applications/text_classification/multi_label/utils.py
  paddlenlp/datasets/wos.py
Labels: text classification

#2665 Support more model outputs for BERT/ERNIE/RoBERTa
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/bert/modeling.py
  paddlenlp/transformers/ernie/modeling.py
  paddlenlp/transformers/model_outputs.py
  paddlenlp/transformers/model_utils.py
  paddlenlp/transformers/roberta/modeling.py
  paddlenlp/transformers/utils.py
Labels: enhancement

#2782 Update RGL README
  examples/few_shot/RGL/README.md
Labels: documentation

#2789 update log for the text classification
  applications/text_classification/hierarchical/train.py
  applications/text_classification/multi_class/train.py
  applications/text_classification/multi_label/train.py
Labels: text classification

#2788 change text classification local dataset format from tsv to txt
  applications/text_classification/README.md
  applications/text_classification/doccano.md
  applications/text_classification/doccano.py
  applications/text_classification/hierarchical/README.md
  applications/text_classification/hierarchical/deploy/predictor/README.md
  applications/text_classification/hierarchical/deploy/predictor/infer.py
  applications/text_classification/hierarchical/predict.py
  applications/text_classification/hierarchical/prune.py
  applications/text_classification/hierarchical/train.py
  applications/text_classification/multi_class/README.md
  applications/text_classification/multi_class/deploy/predictor/README.md
  applications/text_classification/multi_class/deploy/predictor/infer.py
  applications/text_classification/multi_class/predict.py
  applications/text_classification/multi_class/prune.py
  applications/text_classification/multi_class/train.py
  applications/text_classification/multi_label/README.md
  applications/text_classification/multi_label/deploy/predictor/README.md
  applications/text_classification/multi_label/deploy/predictor/infer.py
  applications/text_classification/multi_label/predict.py
  applications/text_classification/multi_label/prune.py
  applications/text_classification/multi_label/train.py
Labels: text classification

#2786 Update faq question for inbatch model loading simcse checkpoint and o…
  applications/neural_search/recall/in_batch_negative/README.md
  applications/neural_search/recall/in_batch_negative/base_model.py
  applications/neural_search/recall/in_batch_negative/scripts/train_batch_neg.sh
  applications/neural_search/recall/in_batch_negative/train_batch_neg.py
  applications/neural_search/recall/milvus/README.md
  applications/neural_search/recall/simcse/README.md
Labels: documentation, bugfix, pipelines

#2754 Add CodeGen to taskflow
  docs/model_zoo/taskflow.md
  paddlenlp/taskflow/code_generation.py
  paddlenlp/taskflow/taskflow.py
Labels: taskflow

#2329 [ernie-health] add deploy
  model_zoo/ernie-health/README.md
  model_zoo/ernie-health/cblue/README.md
  model_zoo/ernie-health/cblue/export_model.py
  model_zoo/ernie-health/cblue/utils.py
  model_zoo/ernie-health/deploy/predictor/README.md
  model_zoo/ernie-health/deploy/predictor/infer_classification.py
  model_zoo/ernie-health/deploy/predictor/infer_ner.py
  model_zoo/ernie-health/deploy/predictor/infer_spo.py
  model_zoo/ernie-health/deploy/predictor/predictor.py
  model_zoo/ernie-health/deploy/predictor/requirements_cpu.txt
  model_zoo/ernie-health/deploy/predictor/requirements_gpu.txt
Labels: deploy

#2867 [duie] fix NameError brought by using AutoTokenizer
  examples/information_extraction/DuIE/data_loader.py
Labels: bugfix

#2855 Add UIE english model
  docs/model_zoo/taskflow.md
  model_zoo/uie/README.md
  model_zoo/uie/deploy/python/uie_predictor.py
  paddlenlp/taskflow/information_extraction.py
  paddlenlp/taskflow/taskflow.py
Labels: ie

#2842 Update requirements.txt and README of pipelines
  applications/experimental/pipelines/examples/question-answering/README.md
  applications/experimental/pipelines/examples/semantic-search/README.md
  applications/experimental/pipelines/pipelines/nodes/file_converter/pdf.py
  applications/experimental/pipelines/requirements.txt
  applications/experimental/pipelines/rest_api/application.py
  applications/experimental/pipelines/scripts/run_qa_server.sh
  applications/experimental/pipelines/scripts/run_qa_web.sh
  applications/experimental/pipelines/scripts/run_search_server.sh
  applications/experimental/pipelines/scripts/run_search_web.sh
  applications/experimental/pipelines/utils/offline_ann.py
Labels: enhancement, pipelines

#2883 Fix auto usage
  examples/few_shot/efl/train.py
  examples/information_extraction/DuEE/classifier.py
  examples/information_extraction/DuEE/sequence_labeling.py
  examples/semantic_indexing/recall.py
  tests/ernie_information_extraction/export_model.py
Labels: bugfix

#2902 Change test_pairwise.csv to dev_pairwise.csv of neural search
  applications/neural_search/ranking/ernie_matching/scripts/train_pairwise.sh
Labels: bugfix, pipelines

#2805 add data augmentation strategy
  paddlenlp/__init__.py
  paddlenlp/data_augmentation/__init__.py
  paddlenlp/data_augmentation/base_augment.py
  paddlenlp/data_augmentation/word/__init__.py
  paddlenlp/data_augmentation/word/word_delete.py
  paddlenlp/data_augmentation/word/word_insert.py
  paddlenlp/data_augmentation/word/word_substitute.py
  paddlenlp/data_augmentation/word/word_swap.py
Labels: data augmentation
