Repository PaddlePaddle/PaddleNLP, pull requests merged in 2022-12, with the labels that each got.

#3979 Update requirements& fix multi recall bugs of PIpelines
  pipelines/examples/semantic-search/multi_recall_semantic_search_example.py
  pipelines/requirements.txt
Labels: bugfix, pipelines

#3955 remove redundant tag
  docs/model_zoo/taskflow.md
Labels: contributor, status: proposed

#3984 【fix benchmark】
  tests/test_tipc/static/dp/bert/benchmark_common/run_benchmark.sh
  tests/test_tipc/static/dp/gpt/benchmark_common/run_benchmark.sh
  tests/test_tipc/static/dp/transformer/benchmark_common/run_benchmark.sh
Labels: contributor, status: proposed

#3991 Add automatic deploy for pipelines
  .github/workflows/pypi.yml
  Makefile
  pipelines/Makefile
  pipelines/VERSION
  pipelines/pipelines/__init__.py
  pipelines/pipelines/version.py
  pipelines/setup.py
  scripts/should_deploy.py
Labels: enhancement, pipelines

#4017 [PPDiffusers] release 0.9.0
  ppdiffusers/README.md
  ppdiffusers/VERSION
Labels: contributor, status: proposed

#3982 [HF] Implement save_to_hf_hub for Model and Tokenizer
  paddlenlp/transformers/model_utils.py
  paddlenlp/transformers/tokenizer_utils_base.py
Labels: hf_integration

#4018 [PPDiffusers] update readme add more weights
  ppdiffusers/README.md
Labels: contributor, status: proposed

#4035 [NewFeature] add hf config solution
  Makefile
  paddlenlp/transformers/configuration_utils.py
  paddlenlp/transformers/model_utils.py
  paddlenlp/transformers/utils.py
  paddlenlp/utils/__init__.py
  paddlenlp/utils/env.py
  tests/transformers/test_configuration_utils.py
Labels: PR:ready for revivew

#4039 [HF] Enable text summarization taskflow to load from HF Hub
  paddlenlp/taskflow/text_summarization.py
Labels: hf_integration

#4028 [prompt] add unittest for template apis
  Makefile
  paddlenlp/prompt/prompt_tokenizer.py
  paddlenlp/prompt/template.py
  tests/prompt/__init__.py
  tests/prompt/test_template.py
Labels: prompt

#4049 Fix Model config of ERNIE 3.0 Tiny v2
  paddlenlp/transformers/ernie/modeling.py
Labels: model-compression

#3977 add NoRepeatNGramLogitsProcessor
  paddlenlp/transformers/generation_utils.py
Labels: contributor, status: proposed

#4021 [Prompt] PromptModelForSequenceClassification and unit tests
  paddlenlp/prompt/__init__.py
  paddlenlp/prompt/prompt_model.py
  paddlenlp/prompt/prompt_trainer.py
  tests/prompt/test_prompt_model.py
Labels: prompt

#4041 Add config testing
  paddlenlp/transformers/configuration_utils.py
  paddlenlp/transformers/model_utils.py
  paddlenlp/transformers/pegasus/modeling.py
  tests/transformers/bert/test_modeling.py
  tests/transformers/test_modeling_common.py
Labels: PR:ready for revivew

#4079 Fix input names for uie
  model_zoo/uie/README.md
  model_zoo/uie/evaluate.py
  model_zoo/uie/utils.py
Labels: bugfix

#4080 update uie-x performance
  applications/information_extraction/document/README.md
Labels: ie, application

#4083 [HF] make AutoModel compatible with standard config and legacy config
  paddlenlp/transformers/auto/modeling.py
  paddlenlp/utils/downloader.py
Labels: hf_integration

#4067 Update README.md
  README_cn.md
  README_en.md
  applications/information_extraction/taskflow_doc.md
Labels: documentation

#3968 Support multi-label setup in Text Classification Taskflow
  paddlenlp/taskflow/taskflow.py
  paddlenlp/taskflow/text_classification.py
  tests/taskflow/test_text_classification.py
Labels: taskflow

#4114 [PPDiffusers] support recompute
  ppdiffusers/examples/text_to_image_laion400m/README.md
  ppdiffusers/examples/text_to_image_laion400m/ldm/ldm_args.py
  ppdiffusers/examples/text_to_image_laion400m/ldm/model.py
  ppdiffusers/examples/text_to_image_laion400m/train_txt2img_laion400m_no_trainer.py
  ppdiffusers/examples/text_to_image_laion400m/train_txt2img_laion400m_trainer.py
Labels: contributor, status: proposed

#4102 optimize code details pull-request, test=develop
  applications/text_summarization/pegasus/README.md
  applications/text_summarization/pegasus/deploy/paddle_inference/inference_pegasus.py
  applications/text_summarization/pegasus/deploy/paddle_serving/pipeline_client.py
  applications/text_summarization/pegasus/deploy/paddle_serving/pipeline_service.py
  applications/text_summarization/pegasus/export_model.py
  applications/text_summarization/pegasus/export_model.sh
  applications/text_summarization/pegasus/predict.py
  applications/text_summarization/pegasus/run_prepare.py
  applications/text_summarization/pegasus/run_train.sh
  applications/text_summarization/pegasus/train.py
  applications/text_summarization/pegasus/utils.py
Labels: contributor, status: proposed

#4130 Add HF Space Link for UIE-X
  applications/information_extraction/README.md
Labels: documentation, ie

#4153 Skip labels not in schema for entity extraction
  applications/information_extraction/text/data_distill/README.md
  applications/information_extraction/text/data_distill/utils.py
Labels: ie

#4163 Support set_argument method for UIE
  paddlenlp/taskflow/information_extraction.py
  paddlenlp/taskflow/taskflow.py
Labels: taskflow, ie

#4219 Fix PyPI release again
  .github/workflows/release.yml
Labels: status: not progressed

#3945 add ERNIE-CTM configuration class and move ERNIE-CTM modeling and rel…
  paddlenlp/taskflow/knowledge_mining.py
  paddlenlp/transformers/ernie_ctm/configuration.py
  paddlenlp/transformers/ernie_ctm/modeling.py
Labels: contributor, status: proposed

#4279 update text classification
  applications/text_classification/hierarchical/README.md
  applications/text_classification/hierarchical/analysis/README.md
  applications/text_classification/hierarchical/analysis/aug.py
  applications/text_classification/hierarchical/analysis/dirty.py
  applications/text_classification/hierarchical/analysis/evaluate.py
  applications/text_classification/hierarchical/analysis/sent_interpret.py
  applications/text_classification/hierarchical/analysis/sparse.py
  applications/text_classification/hierarchical/analysis/word_interpret.ipynb
  applications/text_classification/hierarchical/deploy/predictor/README.md
  applications/text_classification/hierarchical/deploy/predictor/infer.py
  applications/text_classification/hierarchical/deploy/predictor/predictor.py
  applications/text_classification/multi_class/README.md
  applications/text_classification/multi_class/analysis/README.md
  applications/text_classification/multi_class/analysis/aug.py
  applications/text_classification/multi_class/analysis/dirty.py
  applications/text_classification/multi_class/analysis/evaluate.py
  applications/text_classification/multi_class/analysis/sent_interpret.py
  applications/text_classification/multi_class/analysis/sparse.py
  applications/text_classification/multi_class/analysis/word_interpret.ipynb
  applications/text_classification/multi_class/deploy/predictor/README.md
  applications/text_classification/multi_class/deploy/predictor/infer.py
  applications/text_classification/multi_class/deploy/predictor/predictor.py
  applications/text_classification/multi_label/README.md
  applications/text_classification/multi_label/analysis/README.md
  applications/text_classification/multi_label/analysis/aug.py
  applications/text_classification/multi_label/analysis/dirty.py
  applications/text_classification/multi_label/analysis/evaluate.py
  applications/text_classification/multi_label/analysis/sent_interpret.py
  applications/text_classification/multi_label/analysis/sparse.py
  applications/text_classification/multi_label/analysis/word_interpret.ipynb
  applications/text_classification/multi_label/deploy/predictor/README.md
  applications/text_classification/multi_label/deploy/predictor/infer.py
  applications/text_classification/multi_label/deploy/predictor/predictor.py
  applications/text_classification/multi_label/prune.py
Labels: text classification

#4249 【CI】 add ci scripts
  Makefile
  scripts/regression/README.md
  scripts/regression/ci_case.sh
  scripts/regression/ci_normal_case.py
  scripts/regression/get_model_list.py
  scripts/regression/requirements_ci.txt
  scripts/regression/run_ci.sh
  scripts/regression/run_release.sh
  scripts/regression/test_taskflow.py
Labels: contributor, status: proposed
