Repository PaddlePaddle/PaddleNLP, pull requests merged in 2022-05, with the labels that each got.

#2061 Add ONNX Export
  paddlenlp/trainer/trainer_base.py
  requirements.txt
Labels: enhancement

#2070 fix bug: NPTag postprocess
  paddlenlp/taskflow/knowledge_mining.py
Labels: bugfix

#2092 [BugFix] Fix ernie gen mode load
  paddlenlp/transformers/ernie_gen/modeling.py
Labels: bugfix

#2056 [NEW Model] Add RoFormerV2
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/auto/modeling.py
  paddlenlp/transformers/auto/tokenizer.py
  paddlenlp/transformers/roformerv2/__init__.py
  paddlenlp/transformers/roformerv2/modeling.py
  paddlenlp/transformers/roformerv2/tokenizer.py
Labels: contributions

#2150 Move faster_generation to top level.
  examples/dialogue/plato-xl
  faster_generation/README.md
  faster_generation/perf/README.md
  faster_generation/perf/bart_perf.py
  faster_generation/perf/gpt_perf.py
  faster_generation/perf/run_perf_bart.sh
  faster_generation/perf/run_perf_gpt.sh
  faster_generation/samples/gpt_mp_sample.py
  faster_generation/samples/gpt_sample.py
  faster_generation/samples/mbart_sample.py
  faster_generation/samples/plato_sample.py
  faster_generation/samples/plato_xl_sample.py
  faster_generation/samples/unimo_text_sample.py
  model_zoo/plato-xl/README.md
  model_zoo/plato-xl/infer.py
Labels: faster

#2199 Fix NPTag preprocess bug
  paddlenlp/taskflow/knowledge_mining.py
Labels: bugfix

#2209 fix bug: add parameter encoding='utf-8' while opening vocab.bpe
  paddlenlp/transformers/tokenizer_utils.py
Labels: bugfix

#2264 Update negative example generation method for UIE
  docs/model_zoo/taskflow.md
  model_zoo/uie/README.md
  model_zoo/uie/doccano.md
  model_zoo/uie/doccano.py
  model_zoo/uie/finetune.py
  model_zoo/uie/utils.py
Labels: ie

#2088 [NEW Model] Add GAU-alpha model
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/auto/modeling.py
  paddlenlp/transformers/auto/tokenizer.py
  paddlenlp/transformers/gau_alpha/__init__.py
  paddlenlp/transformers/gau_alpha/modeling.py
  paddlenlp/transformers/gau_alpha/tokenizer.py
Labels: contributions
