Repository PaddlePaddle/PaddleNLP, pull requests merged in 2023-08, with the labels that each got.

#6566 [benchmark]disable sd t5
  tests/test_tipc/configs/stable_diffusion_model/train_infer_python.txt
  tests/test_tipc/configs/t5_for_conditional_generation/train_infer_python.txt
Labels: contributor, status: proposed

#6582 [PPDiffusers] 迁移benchmark内容
  paddlenlp/trainer/argparser.py
  tests/test_tipc/configs/latent_diffusion_model/train_infer_python.txt
  tests/test_tipc/configs/stable_diffusion_model/train_infer_python.txt
  tests/test_tipc/prepare.sh
Labels: contributor, status: proposed

#6589 update auto_base for PaddleNLP#6431
  scripts/regression/ci_gpt-3.sh
Labels: contributor, status: proposed

#6615 [benchmark] add proxy when git clone paddlemix
  tests/test_tipc/prepare.sh
Labels: contributor, status: proposed

#6613 [Paddle-pipelines] Update m3e_retriever
  pipelines/examples/chatbot/ParallelRetriever_example.py
  pipelines/examples/chatbot/README_ParallelRetriever.md
  pipelines/pipelines/nodes/retriever/__init__.py
  pipelines/pipelines/nodes/retriever/parallel_retriever.py
Labels: pipelines, contributor, status: proposed

#6624 fix asynchronize save
  paddlenlp/trainer/trainer.py
Labels: contributor, status: proposed

#6627 update clip clipseg
  paddlenlp/transformers/clip/configuration.py
  paddlenlp/transformers/clip/modeling.py
  paddlenlp/transformers/clip/tokenizer.py
  paddlenlp/transformers/clipseg/configuration.py
  paddlenlp/transformers/clipseg/modeling.py
Labels: contributor, status: proposed

#6629 [Paddle-pipelines] Fix debug logger slow speed bug
  pipelines/examples/chatbot/ParallelRetriever_example.py
  pipelines/examples/chatbot/README_ParallelRetriever.md
  pipelines/examples/chatbot/config.pbtxt
  pipelines/pipelines/pipelines/base.py
Labels: pipelines, contributor, status: proposed

#6638 [pipelines benchmark] add T2Ranking_test.py
  pipelines/benchmarks/README.md
  pipelines/benchmarks/Retrieval_benchmarks.py
  pipelines/benchmarks/requirements.txt
Labels: pipelines, contributor, status: proposed

#6641 Update paddlenlp develop
  paddlenlp/trainer/plugins/timer.py
  paddlenlp/trainer/trainer.py
  paddlenlp/trainer/trainer_utils.py
  paddlenlp/trainer/training_args.py
Labels: contributor, status: proposed

#6698 fix loop
  paddlenlp/trainer/trainer.py
Labels: contributor, status: proposed

#6708 rm llama benchmark args
  tests/test_tipc/configs/llama/train_infer_python.txt
Labels: contributor, status: proposed

#6710 fix(llama): add pretrained_init_configuration to LlamaConfig
  paddlenlp/transformers/llama/configuration.py
Labels: contributor, status: proposed

#6737 [Paddle-pipelines] Add ERNIE-Bot-turbo support
  pipelines/pipelines/nodes/llm/ernie_bot.py
Labels: pipelines, contributor, status: proposed

#6738 [gpt-3]del PADDLE_USE_FOUR_DIRECTIONS_P2P flag
  model_zoo/gpt-3/benchmarks/test_tipc/gpt/dygraph/hybrid_parallel/benchmark_common/run_benchmark.sh
  scripts/regression/ci_gpt-3.sh
Labels: contributor, status: proposed

#6685 [Paddle-pipelines] upload chatfile2.py
  pipelines/examples/chatpaper/README.md
  pipelines/examples/chatpaper/chat_paper.py
  pipelines/examples/chatpaper/create_base.py
  pipelines/examples/chatpaper/requirements.txt
  pipelines/examples/chatpaper/utils.py
  pipelines/pipelines/document_stores/faiss.py
  pipelines/pipelines/nodes/combine_documents/__init__.py
  pipelines/pipelines/nodes/combine_documents/base.py
  pipelines/pipelines/nodes/combine_documents/map_reduce.py
  pipelines/pipelines/nodes/combine_documents/reduce.py
  pipelines/pipelines/nodes/combine_documents/stuff.py
  pipelines/tests/nodes/combine_documents/test_combinedocuments.py
Labels: pipelines, contributor, status: proposed

#6764 Update README_en.md to fix a series of spell errors
  README_en.md
Labels: contributor, status: proposed

#6760 [Paddle-pipelines] update chat_paper.py
  pipelines/examples/chatpaper/README.md
  pipelines/examples/chatpaper/chat_paper.py
  pipelines/examples/chatpaper/create_index.py
  pipelines/examples/chatpaper/utils.py
  pipelines/pipelines/nodes/combine_documents/map_reduce.py
  pipelines/pipelines/nodes/combine_documents/stuff.py
Labels: pipelines, contributor, status: proposed

#6729 [Paddle-pipelines] Add logging error
  pipelines/pipelines/nodes/retriever/parallel_retriever.py
Labels: pipelines

#6768 [PaddlePipelines] upload ChatTable
  pipelines/examples/chat_table/README.md
  pipelines/examples/chat_table/chat_table_web.py
  pipelines/examples/chat_table/utils.py
Labels: pipelines, contributor, status: proposed

#6779 [Paddle-pipelines] Update pipelines to 0.6.0
  pipelines/VERSION
Labels: pipelines

#6790 [Paddle-pipelines] Update pipelines
  pipelines/examples/chatpaper/chat_paper.py
  pipelines/pipelines/nodes/retriever/base.py
  pipelines/setup.py
Labels: pipelines

#6825 [Bug fixes] profiler export path not work
  paddlenlp/utils/profiler.py
Labels: contributor, status: proposed

#6828 [CI] fix ernie 1.0
  scripts/regression/ci_case.sh
Labels: contributor

#6849 [gpt-3]update auto benchmark
  model_zoo/gpt-3/benchmarks/test_tipc/gpt/static/auto_parallel/benchmark_common/run_benchmark.sh
Labels: contributor
