Repository PaddlePaddle/PaddleNLP, pull requests merged in 2023-01, with the labels that each got.

#4040 fix(sec): upgrade streamlit to 1.11.1
  pipelines/requirements.txt
Labels: contributor, status: proposed

#4228 bugfix on step4
  examples/torch_migration/pipeline/Step4/check_step4.py
  examples/torch_migration/pipeline/Step4/test_bp.py
Labels: contributor, status: not progressed

#4336 [PPDiffusers] fix dead link and add sd License
  ppdiffusers/README.md
Labels: bug

#4300 Fix version 2.4.9 bugs for pipelines
  paddlenlp/transformers/semantic_search/modeling.py
  pipelines/examples/semantic-search/semantic_search_example.py
  pipelines/pipelines/document_stores/elasticsearch.py
  pipelines/pipelines/nodes/ranker/ernie_ranker.py
  pipelines/rest_api/controller/search.py
  pipelines/rest_api/schema.py
  pipelines/utils/offline_ann.py
Labels: pipelines

#4331 [T5] add prepare_decoder_input_ids_from_labels method
  paddlenlp/transformers/t5/modeling.py
Labels: contributor, status: proposed

#3728 AutoNLP TrainerBase and Text Classification
  Makefile
  paddlenlp/experimental/autonlp/README.md
  paddlenlp/experimental/autonlp/README_en.md
  paddlenlp/experimental/autonlp/__init__.py
  paddlenlp/experimental/autonlp/auto_trainer_base.py
  paddlenlp/experimental/autonlp/requirements.txt
  paddlenlp/experimental/autonlp/text_classification.py
  paddlenlp/taskflow/text_classification.py
  pyproject.toml
  requirements-dev.txt
  setup.py
  tests/experimental/autonlp/__init__.py
  tests/experimental/autonlp/test_text_classification.py
  tests/fixtures/dummy/divorce/dev.txt
  tests/fixtures/dummy/divorce/train.txt
  tests/fixtures/dummy/tnews/dev.json
Labels: autonlp

#4356 update paddleslim version for text classification application
  applications/text_classification/hierarchical/README.md
  applications/text_classification/multi_class/README.md
  applications/text_classification/multi_label/README.md
Labels: text classification

#4366 Fix taskflow unittest
  scripts/regression/ci_case.sh
  scripts/regression/ci_normal_case.py
  scripts/regression/requirements_ci.txt
  scripts/regression/run_ci.sh
  scripts/regression/run_release.sh
Labels: contributor, status: proposed

#4371 add opencv-contrib-python
  scripts/regression/ci_case.sh
  scripts/regression/requirements_ci.txt
  scripts/regression/run_ci.sh
Labels: contributor, status: proposed

#4383 Fix load_torch
  paddlenlp/utils/serialization.py
Labels: contributor, status: proposed

#4011 Add ERNIE Tiny in model zoo
  model_zoo/ernie-3.0/README.md
  model_zoo/ernie-tiny/README.md
  model_zoo/ernie-tiny/data/intent_label.txt
  model_zoo/ernie-tiny/data/slot_label.txt
  model_zoo/ernie-tiny/model.py
  model_zoo/ernie-tiny/run_eval.py
  model_zoo/ernie-tiny/run_train.py
  model_zoo/ernie-tiny/utils.py
  paddlenlp/trainer/compression_args.py
  paddlenlp/trainer/trainer.py
  paddlenlp/trainer/trainer_compress.py
  paddlenlp/transformers/ofa_utils.py
Labels: deploy, model-compression

#4388 [NEW Model] add cmsim lock
  paddlenlp.zip
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/auto/modeling.py
  paddlenlp/transformers/auto/tokenizer.py
  paddlenlp/transformers/cmsim_lock/__init__.py
  paddlenlp/transformers/cmsim_lock/configuration.py
  paddlenlp/transformers/cmsim_lock/feature_extraction.py
  paddlenlp/transformers/cmsim_lock/image_processing.py
  paddlenlp/transformers/cmsim_lock/modeling.py
  paddlenlp/transformers/cmsim_lock/procesing.py
  paddlenlp/transformers/cmsim_lock/tokenizer.py
  tests/transformers/cmsim_lock/__init__.py
  tests/transformers/cmsim_lock/test_modeling.py
Labels: transformers

#4434 rm paddlenlp.zip
  paddlenlp.zip
Labels: contributor, status: proposed

#4422 Update ERNIE Tiny doc
  model_zoo/ernie-tiny/README.md
Labels: documentation

#4455 [CI] updata paddlenlp install ways
  scripts/regression/run_ci.sh
  scripts/regression/run_release.sh
Labels: contributor, status: proposed

#4435 support simple serving for ernie-m text classification
  applications/text_classification/hierarchical/deploy/simple_serving/README.md
  applications/text_classification/hierarchical/deploy/simple_serving/ernie_m_server.py
  applications/text_classification/multi_class/deploy/simple_serving/README.md
  applications/text_classification/multi_class/deploy/simple_serving/ernie_m_server.py
  applications/text_classification/multi_label/deploy/simple_serving/README.md
  applications/text_classification/multi_label/deploy/simple_serving/ernie_m_server.py
  paddlenlp/server/handlers/__init__.py
  paddlenlp/server/handlers/custom_model_handler.py
Labels: text classification

#4480 Revert "[NEW Model] add cmsim lock"
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/auto/modeling.py
  paddlenlp/transformers/auto/tokenizer.py
  paddlenlp/transformers/cmsim_lock/__init__.py
  paddlenlp/transformers/cmsim_lock/configuration.py
  paddlenlp/transformers/cmsim_lock/feature_extraction.py
  paddlenlp/transformers/cmsim_lock/image_processing.py
  paddlenlp/transformers/cmsim_lock/modeling.py
  paddlenlp/transformers/cmsim_lock/procesing.py
  paddlenlp/transformers/cmsim_lock/tokenizer.py
  tests/transformers/cmsim_lock/__init__.py
  tests/transformers/cmsim_lock/test_modeling.py
Labels: contributor, status: proposed

#4491 fix download error multi gpu or multi node
  paddlenlp/transformers/model_utils.py
Labels: contributor, status: proposed

#4519 Fix Deprecation Warning for Sentence Dataaug
  paddlenlp/dataaug/sentence.py
Labels: data augmentation

#4534 Update README.md , because of Wrong year
  ppdiffusers/README.md
Labels: contributor, status: proposed

#4540 Update transformer_encoder.py
  applications/document_intelligence/doc_vqa/Rerank/src/model/transformer_encoder.py
Labels: contributor, status: proposed

#4539 Update ernie.py
  applications/document_intelligence/doc_vqa/Rerank/src/model/ernie.py
Labels: contributor, status: proposed

#4546 Update README_en.md
  applications/information_extraction/document/README_en.md
Labels: contributor, status: proposed

#4544 Update client.py
  applications/information_extraction/document/deploy/simple_serving/client.py
Labels: contributor, status: proposed

#4547 Update train.py
  applications/information_extraction/text/data_distill/train.py
Labels: contributor, status: proposed

#4541 Update tokenization.py
  applications/document_intelligence/doc_vqa/Rerank/src/tokenization.py
Labels: contributor, status: proposed

#4542 Update train_ce.py
  applications/document_intelligence/doc_vqa/Rerank/src/train_ce.py
Labels: contributor, status: proposed

#4549 Update export_to_serving.py
  applications/neural_search/ranking/cross_encoder/export_to_serving.py
Labels: contributor, status: proposed

#4548 Update README_en.md
  applications/information_extraction/text/README_en.md
Labels: contributor, status: proposed

#4552 Update data.py
  applications/neural_search/recall/in_batch_negative/data.py
Labels: contributor, status: proposed

#4550 Update data.py
  applications/neural_search/ranking/ernie_matching/data.py
Labels: contributor, status: proposed

#4556 Update base_model.py
  applications/neural_search/recall/milvus/base_model.py
  applications/neural_search/recall/milvus/data.py
  applications/neural_search/recall/milvus/inference.py
Labels: contributor, status: proposed

#4551 Update base_model.py
  applications/neural_search/recall/in_batch_negative/base_model.py
Labels: contributor, status: proposed

#4553 Update evaluate.py
  applications/neural_search/recall/in_batch_negative/evaluate.py
Labels: contributor, status: proposed

#4554 Update inference.py
  applications/neural_search/recall/in_batch_negative/inference.py
Labels: contributor, status: proposed

#4555 Update train_batch_neg.py
  applications/neural_search/recall/in_batch_negative/train_batch_neg.py
Labels: contributor, status: proposed

#4559 Fix param warmup_proportion
  applications/text_summarization/unimo-text/train.py
Labels: contributor, status: proposed

#4560 Fix some words
  applications/question_answering/unsupervised_qa/finetune/answer_extraction_and_roundtrip_filtration/finetune.py
  applications/question_answering/unsupervised_qa/run_corpus_preparation.py
  applications/question_answering/unsupervised_qa/run_data_preprocess.py
  applications/question_answering/unsupervised_qa/run_pipelines_example.py
  applications/question_answering/unsupervised_qa/run_qa_pairs_generation.py
  applications/question_answering/unsupervised_qa/tools/create_synthetic_answer.py
  applications/question_answering/unsupervised_qa/tools/question_coverage.py
  applications/sentiment_analysis/ASO_analysis/classification/evaluate.py
  applications/sentiment_analysis/ASO_analysis/classification/train.py
  applications/sentiment_analysis/ASO_analysis/export_model.py
  applications/sentiment_analysis/ASO_analysis/extraction/evaluate.py
  applications/sentiment_analysis/ASO_analysis/extraction/train.py
  applications/sentiment_analysis/ASO_analysis/pp_minilm/evaluate.py
  applications/sentiment_analysis/ASO_analysis/pp_minilm/performance_test.py
  applications/sentiment_analysis/ASO_analysis/predict.py
  applications/sentiment_analysis/unified_sentiment_extraction/label_studio.py
  applications/sentiment_analysis/unified_sentiment_extraction/visual_analysis.py
Labels: contributor, status: proposed

#4567 update prune.py for text classification
  applications/text_classification/hierarchical/prune.py
  applications/text_classification/multi_label/prune.py
Labels: text classification

#4575 [Nezha P0] Add PretrainedConfig and unit tests
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/nezha/configuration.py
  paddlenlp/transformers/nezha/modeling.py
  paddlenlp/transformers/nezha/tokenizer.py
  tests/transformers/nezha/__init__.py
  tests/transformers/nezha/test_modeling.py
  tests/transformers/nezha/test_tokenizer.py
Labels: transformers_upgrade

#4408 Add TSDASG model and streaming mode dataset loader
  applications/text_summarization/pegasus/README.md
  applications/text_summarization/pegasus/train.py
  paddlenlp/transformers/pegasus/modeling.py
Labels: text_summarization

#4596 [Nezha P1] Add loss, return_dict, hidden and attention outputs
  paddlenlp/transformers/nezha/modeling.py
  tests/transformers/nezha/test_modeling.py
Labels: transformers_upgrade
