Repository PaddlePaddle/PaddleNLP, pull requests merged in 2023-04, with the labels that each got.

#5514 [Prophetnet P0] Update prophetnet examples
  examples/text_summarization/prophetnet/README.md
  examples/text_summarization/prophetnet/run_train.sh
  examples/text_summarization/prophetnet/train_prophetnet.py
  examples/text_summarization/prophetnet/uncase_tokenize_data.py
  paddlenlp/transformers/prophetnet/__init__.py
Labels: contributor, status: proposed

#5517 [Rembert]add PretrainedConfig and unit test
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/rembert/configuration.py
  paddlenlp/transformers/rembert/modeling.py
  tests/transformers/rembert/__init__.py
  tests/transformers/rembert/test_modeling.py
  tests/transformers/rembert/test_tokenizer.py
Labels: contributor, status: proposed

#5526 [PPDiffusers]update log control image
  ppdiffusers/examples/controlnet/control/model.py
Labels: contributor, status: proposed

#5193 【PaddlePaddle Hackathon 4】[103] 新增tie_weights能力 代码和单元测试
  paddlenlp/transformers/albert/modeling.py
  paddlenlp/transformers/bigbird/modeling.py
  paddlenlp/transformers/electra/modeling.py
  paddlenlp/transformers/fnet/modeling.py
  paddlenlp/transformers/funnel/modeling.py
  paddlenlp/transformers/model_utils.py
  paddlenlp/transformers/reformer/modeling.py
  paddlenlp/transformers/roberta/modeling.py
  tests/prompt/test_verbalizer.py
  tests/transformers/albert/test_modeling.py
  tests/transformers/bert/test_modeling.py
  tests/transformers/bigbird/test_modeling.py
  tests/transformers/electra/test_modeling.py
  tests/transformers/ernie/test_modeling.py
  tests/transformers/gau_alpha/test_modeling.py
  tests/transformers/reformer/test_modeling.py
  tests/transformers/roberta/test_modeling.py
  tests/transformers/roformer/test_modeling.py
  tests/transformers/test_modeling_common.py
Labels: hackathon, contributor, status: proposed

#5554 [gpt-3]update auto loss_base for #5511 & fix ci_bug
  scripts/regression/ci_case.sh
  scripts/regression/ci_gpt-3.sh
Labels: contributor, status: proposed

#5562 [benchmark] fix bertqa and PPMiniLM tests bug
  paddlenlp/transformers/ppminilm/modeling.py
  paddlenlp/transformers/reformer/modeling.py
  ppdiffusers/ppdiffusers/ppnlp_patch_utils.py
Labels: contributor, status: proposed

#5565 [PPDiffusers] remove patch size pt
  ppdiffusers/ppdiffusers/ppnlp_patch_utils.py
  ppdiffusers/ppdiffusers/schedulers/scheduling_heun_discrete.py
Labels: contributor, status: proposed

#5560 [Luke]add PretrainedConfig and unit test
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/luke/configuration.py
  paddlenlp/transformers/luke/modeling.py
  paddlenlp/transformers/luke/tokenizer.py
  tests/transformers/luke/__init__.py
  tests/transformers/luke/test_modeling.py
  tests/transformers/luke/test_tokenizer.py
Labels: contributor, status: proposed

#5619 [PPDiffusers] update text2img_laion400M
  ppdiffusers/examples/text_to_image_laion400m/data/filelist/laion_aes.filelist
  ppdiffusers/examples/text_to_image_laion400m/data/filelist/laion_aes.filelist.list
  ppdiffusers/examples/text_to_image_laion400m/ldm/ldm_args.py
  ppdiffusers/examples/text_to_image_laion400m/ldm/model.py
  ppdiffusers/examples/text_to_image_laion400m/ldm/text_image_pair_dataset.py
  ppdiffusers/examples/text_to_image_laion400m/train_txt2img_laion400m_trainer.py
  ppdiffusers/ppdiffusers/patches/ppnlp_patch_utils.py
  ppdiffusers/ppdiffusers/pipelines/pipeline_utils.py
  ppdiffusers/ppdiffusers/utils/paddle_utils.py
Labels: contributor, status: proposed

#5586 [PPDiffusers] add webui pipeline
  ppdiffusers/README.md
  ppdiffusers/examples/Stable-CycleDiffusion/README.md
  ppdiffusers/examples/community/README.md
  ppdiffusers/examples/community/webui_stable_diffusion.py
  ppdiffusers/examples/dreambooth/README.md
  ppdiffusers/examples/text_to_image/README.md
  ppdiffusers/examples/textual_inversion/README.md
  ppdiffusers/ppdiffusers/schedulers/scheduling_unipc_multistep.py
  ppdiffusers/ppdiffusers/utils/dynamic_modules_utils.py
Labels: contributor, status: proposed

#5631 [PPDiffusers]t2v_support_fp16
  paddlenlp/utils/serialization.py
  ppdiffusers/ppdiffusers/models/unet_3d_condition.py
  ppdiffusers/ppdiffusers/patches/ppnlp_patch_utils.py
  ppdiffusers/ppdiffusers/utils/load_utils.py
Labels: contributor, status: proposed

#5628 [ppdiffusers] release ppdiffusers 0141
  ppdiffusers/VERSION
  ppdiffusers/ppdiffusers/version.py
  ppdiffusers/scripts/fid_clip_score/compute_fid_clip_score.py
Labels: contributor, status: proposed

#5622 fix [Errno 13] Permission denied in windows
  pipelines/pipelines/nodes/file_converter/pdf.py
Labels: pipelines, contributor, status: not progressed

#5644 [PPDiffusers] Fix config cache
  ppdiffusers/ppdiffusers/patches/ppnlp_patch_utils.py
  ppdiffusers/ppdiffusers/pipelines/pipeline_utils.py
  ppdiffusers/ppdiffusers/utils/download_utils.py
Labels: contributor, status: proposed

#5659 【lora】support mp in from_pretrained and save_pretrained
  examples/language_model/bloom/README.md
  examples/language_model/bloom/finetune_generation.py
  examples/language_model/bloom/predict_generation.py
  examples/language_model/bloom/utils.py
  examples/language_model/glm/finetune_generation.py
  examples/language_model/glm/predict_generation.py
  examples/language_model/llama/finetune_generation.py
  paddlenlp/layers/lora.py
Labels: lora

#5667 [Lora] support lora model train and eval
  paddlenlp/layers/lora.py
Labels: lora

#5658 【Hackathon 4th No.102】给AutoConverter增加新的模型组网的支持 Electra
  paddlenlp/transformers/electra/modeling.py
  tests/transformers/electra/test_modeling.py
Labels: hackathon, contributor, status: proposed

#5668 【Hackathon 4th No.102】给AutoConverter增加新的模型组网的支持 Bart
  paddlenlp/transformers/bart/converter.py
  paddlenlp/transformers/bart/modeling.py
  tests/transformers/bart/test_modeling.py
Labels: contributor, status: proposed

#5672 【Hackathon 4th No.102】给AutoConverter增加新的模型组网的支持 Distilbert
  paddlenlp/transformers/distilbert/configuration.py
  paddlenlp/transformers/distilbert/modeling.py
  tests/transformers/distilbert/test_modeling.py
Labels: contributor, status: proposed

#5626 【Hackathon 4th No.102】给AutoConverter增加新的模型组网的支持 AlbertModel
  paddlenlp/transformers/albert/modeling.py
  tests/transformers/albert/test_modeling.py
Labels: hackathon, contributor, status: proposed

#5595 【Hackathon 4th No.102】给AutoConverter增加新的模型组网的支持 CLIPModel
  paddlenlp/transformers/clip/converter.py
  paddlenlp/transformers/clip/modeling.py
  tests/transformers/clip/test_modeling.py
Labels: hackathon, contributor, status: proposed

#5637 squeezebert & layoutxlm p0升级
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/layoutxlm/configuration.py
  paddlenlp/transformers/layoutxlm/modeling.py
  paddlenlp/transformers/squeezebert/configuration.py
  paddlenlp/transformers/squeezebert/modeling.py
  paddlenlp/transformers/squeezebert/tokenizer.py
  tests/transformers/layoutxml/__init__.py
  tests/transformers/layoutxml/test_modeling.py
  tests/transformers/layoutxml/test_tokenizer.py
  tests/transformers/squeezebert/__init__.py
  tests/transformers/squeezebert/test_modeling.py
  tests/transformers/squeezebert/test_tokenizer.py
Labels: contributor, status: proposed

#5694 Fix electra export model
  model_zoo/electra/export_model.py
  scripts/regression/ci_case.sh
Labels: contributor, status: proposed

#5378 [LLM] Add t5 Pre-training and support tensor parallel
  examples/language_model/t5/dataset_utils.py
  examples/language_model/t5/t5_dataset.py
  examples/language_model/t5/t5_run_pretrain_trainer.py
  examples/language_model/t5/tests/t5_mp.py
  examples/language_model/t5/tests/test_parallel_dygraph_dataparallel.py
  examples/language_model/t5/tests/test_t5_mp.py
  model_zoo/ernie-1.0/data_tools/dataset_utils.py
  model_zoo/ernie-1.0/preprocess/create_pretraining_data.py
  paddlenlp/transformers/t5/modeling.py
Labels: contributor, status: not progressed

#5705 [Funnel P0]add PretrainedConfig and unit test
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/funnel/configuration.py
  paddlenlp/transformers/funnel/modeling.py
  paddlenlp/transformers/funnel/tokenizer.py
  tests/transformers/funnel/__init__.py
  tests/transformers/funnel/test_modeling.py
  tests/transformers/funnel/test_tokenizer.py
Labels: hackathon, contributor, status: proposed

#5741 [BugFix] fix resume rng-state file check
  paddlenlp/trainer/trainer.py
Labels: contributor, status: proposed

#5736 BugFix: GPTChineseTokenizer.get_vocab() not implemented
  paddlenlp/transformers/gpt/tokenizer.py
Labels: contributor, status: proposed

#5758 [Trainer] fix trainer amp inf detection
  paddlenlp/trainer/trainer.py
Labels: contributor, status: proposed

#5765 [bug-fix] hyper parallel failed with > 128 workers
  paddlenlp/trainer/trainer_utils.py
Labels: contributor, status: proposed

#5718 Add instruction data from belle
  examples/language_model/glm/data.py
  examples/language_model/glm/finetune_instruction_generation.py
  examples/language_model/glm/utils.py
  paddlenlp/datasets/__init__.py
  paddlenlp/datasets/bellegroup.py
Labels: contributor, status: proposed
