Repository PaddlePaddle/PaddleNLP, pull requests merged in 2023-03, with the labels that each got.

#4851 [Model Zoo] Refactor Bert usage in Model Zoo
  model_zoo/bert/README.md
  model_zoo/bert/create_pretraining_data.py
  model_zoo/bert/export_model.py
  model_zoo/bert/predict_glue.py
  model_zoo/bert/run_glue.py
  model_zoo/bert/run_glue_trainer.py
  model_zoo/bert/run_pretrain_trainer.py
  scripts/regression/ci_case.sh
  tests/fixtures/model_zoo/bert.yaml
  tests/model_zoo/test_bert.py
Labels: contributor, status: proposed

#4981 [Reformer P1] Add loss, return_dict, hidden and attention outputs
  paddlenlp/transformers/reformer/modeling.py
  tests/transformers/reformer/test_modeling.py
Labels: contributor, status: proposed

#5031 [AutoNLP]unify trial_id, trial_name and trial_dir
  paddlenlp/experimental/autonlp/auto_trainer_base.py
Labels: autonlp

#5040 [CI] change ernie-1.0 datasets
  scripts/regression/ci_case.sh
Labels: contributor, status: not progressed

#5042 [CI] run examples when API changed
  scripts/regression/run_ci.sh
Labels: contributor, status: proposed

#5049 [CI] fix ernie-1.0 typo
  scripts/regression/ci_case.sh
Labels: contributor, status: proposed

#5054 [neural search] Update requirements.txt
  applications/neural_search/requirements.txt
Labels: neural-search, contributor, status: proposed

#5070 【bug fix】Text classification application&example
  applications/text_classification/multi_class/README.md
  applications/text_classification/multi_class/train.py
  examples/text_classification/README.md
Labels: text classification

#4996 [paddle-pipelines]Update python versioin to 3.7.3 and index_name
  pipelines/README.md
  pipelines/examples/FAQ/README.md
  pipelines/examples/image_text_retrieval/README.md
  pipelines/examples/question-answering/README.md
  pipelines/examples/semantic-search/Multi_Recall.md
  pipelines/examples/semantic-search/Neural_Search.md
  pipelines/examples/semantic-search/README.md
  pipelines/examples/text_to_image/README.md
Labels: pipelines

#5074 [CLIP/ChineseCLIP] update proj dim
  paddlenlp/transformers/chineseclip/configuration.py
  paddlenlp/transformers/clip/configuration.py
Labels: contributor, status: proposed

#5073 [paddle-pipelines] flake8 pipelines
  pipelines/pipelines/data_handler/dataset.py
  pipelines/pipelines/data_handler/processor.py
  pipelines/pipelines/document_stores/faiss.py
  pipelines/pipelines/document_stores/filter_utils.py
  pipelines/pipelines/document_stores/sql.py
  pipelines/pipelines/document_stores/utils.py
  pipelines/pipelines/nodes/answer_extractor/answer_extractor.py
  pipelines/pipelines/nodes/answer_extractor/qa_filter.py
  pipelines/pipelines/nodes/base.py
  pipelines/pipelines/nodes/document/document_preprocessor.py
  pipelines/pipelines/nodes/file_classifier/file_type.py
  pipelines/pipelines/nodes/file_converter/docx.py
  pipelines/pipelines/nodes/file_converter/image.py
  pipelines/pipelines/nodes/file_converter/pdf.py
  pipelines/pipelines/nodes/models/neural_search_model.py
  pipelines/pipelines/nodes/preprocessor/preprocessor.py
  pipelines/pipelines/nodes/question_generator/question_generator.py
  pipelines/pipelines/nodes/reader/ernie_dureader.py
  pipelines/pipelines/nodes/retriever/base.py
  pipelines/pipelines/nodes/text_to_image_generator/text_to_image_generator.py
  pipelines/pipelines/pipelines/base.py
  pipelines/pipelines/utils/common_utils.py
  pipelines/pipelines/utils/export_utils.py
  pipelines/pipelines/utils/logger.py
  pipelines/pipelines/utils/tokenization.py
  pipelines/requirements.txt
Labels: pipelines

#5076 [PPDiffusers] text2img typo
  ppdiffusers/examples/text_to_image/train_text_to_image.py
Labels: contributor, status: proposed

#5078 [paddle-pipelines] flake8 pipelines examples,ui,restapi
  pipelines/examples/FAQ/dense_faq_example.py
  pipelines/examples/document-intelligence/docprompt_example.py
  pipelines/examples/question-answering/dense_qa_example.py
  pipelines/examples/text_to_image/text_to_image_example.py
  pipelines/examples/unsupervised-question-answering/offline_question_answer_pairs_generation.py
  pipelines/examples/unsupervised-question-answering/unsupervised_question_answering_example.py
  pipelines/pipelines/utils/export_utils.py
  pipelines/rest_api/application.py
  pipelines/ui/webapp_docprompt_gradio.py
  pipelines/ui/webapp_faq.py
  pipelines/ui/webapp_question_answering.py
  pipelines/ui/webapp_semantic_search.py
  pipelines/ui/webapp_text_to_image.py
  pipelines/ui/webapp_unsupervised_question_answering.py
Labels: pipelines

#5090 [PPDiffusers] update controlnet ema
  ppdiffusers/examples/controlnet/control/model.py
Labels: contributor, status: proposed

#4558 Change instr to outstr
  applications/question_answering/unsupervised_qa/finetune/question_generation/gen_utils.py
Labels: contributor, status: proposed

#5115 [PPDiffusers] fix sde vp dead link
  ppdiffusers/examples/inference/README.md
Labels: contributor, status: proposed

#5109 [Neural Search] Remove sigmoid for paddle inference
  applications/neural_search/ranking/ernie_matching/deploy/python/predict.py
Labels: neural-search

#5097 Add MRR metric
  paddlenlp/metrics/__init__.py
  paddlenlp/metrics/mrr.py
  tests/metrics/test_mrr.py
Labels: contributor, status: proposed

#5117 fix ernie-csc depoly core dumped
  examples/text_correction/ernie-csc/predict.py
  scripts/regression/requirements_ci.txt
  scripts/regression/run_release.sh
Labels: contributor, status: proposed

#5132 [DocParser] Add bbox check
  paddlenlp/utils/doc_parser.py
Labels: ie

#5131 [Roformerv2 P0] Add PretrainedConfig and unit tests
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/roformerv2/configuration.py
  paddlenlp/transformers/roformerv2/modeling.py
  paddlenlp/transformers/roformerv2/tokenizer.py
  tests/transformers/roformerv2/__init__.py
  tests/transformers/roformerv2/test_modeling.py
  tests/transformers/roformerv2/test_tokenizer.py
Labels: contributor, status: proposed

#5127 [Neural Search] change output_emb_size to self.ptm.config.hidden_size
  applications/neural_search/recall/in_batch_negative/base_model.py
  applications/neural_search/recall/milvus/base_model.py
  applications/neural_search/recall/simcse/model.py
Labels: neural-search

#5128 torch_load use ZipFile, support bf16, support torch.nn.Parameter
  paddlenlp/utils/serialization.py
  tests/utils/test_serialization.py
Labels: contributor, status: proposed

#5145 [CI] add requirements-dev.txt
  scripts/regression/run_ci.sh
  scripts/regression/run_release.sh
Labels: contributor, status: proposed

#5123 [Electra P0] Add PretrainedConfig and unit tests
  model_zoo/electra/run_pretrain.py
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/electra/configuration.py
  paddlenlp/transformers/electra/modeling.py
  tests/transformers/electra/test_modeling.py
Labels: contributor, status: proposed

#5069 [DalleBart P0] add PretrainedConfig and unit test
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/dallebart/configuration.py
  paddlenlp/transformers/dallebart/modeling.py
  paddlenlp/transformers/dallebart/tokenizer.py
  requirements-dev.txt
  scripts/regression/requirements_ci.txt
  tests/transformers/dallebart/__init__.py
  tests/transformers/dallebart/test_modeling.py
  tests/transformers/dallebart/test_tokenizer.py
Labels: contributor, status: proposed

#5062 bigbird_examples更新
  examples/language_model/bigbird/run_pretrain.py
  paddlenlp/transformers/bigbird/modeling.py
  paddlenlp/transformers/bigbird/tokenizer.py
  tests/transformers/bigbird/test_tokenizer.py
Labels: contributor, status: proposed

#5147 release ppdiffuser0.11.1
  ppdiffusers/README.md
  ppdiffusers/VERSION
  ppdiffusers/examples/dreambooth/README.md
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_all_in_one.py
Labels: contributor, status: proposed

#4807 [Benchmark] add stablediffusion benchmark
  tests/test_tipc/benchmark/modules/stablediffusion.py
  tests/test_tipc/benchmark/options.py
  tests/test_tipc/configs/stablediffusion/train_infer_python.txt
  tests/test_tipc/prepare.sh
Labels: contributor, status: proposed

#5167 fix npu nn.Pad2D()
  paddlenlp/transformers/generation_utils.py
Labels: contributor, status: proposed

#5098 【PaddlePaddle Hackathon 4】[103] 新增tie_weights能力 提交rfc文档
  docs/community/rfcs/20230304_api_design_for_tie_weight_task_103.md
  docs/community/rfcs/api_design_template.md
Labels: contributor, status: proposed

#5170 [CI] add codegen
  scripts/regression/ci_case.sh
  scripts/regression/run_release.sh
  scripts/regression/test_taskflow.py
Labels: contributor, status: proposed

#5186 [BigBird P2] Add inputs_embeds
  paddlenlp/transformers/bigbird/modeling.py
  tests/transformers/bigbird/test_modeling.py
Labels: contributor, status: proposed

#5175 [Reformer P2] Add inputs_embeds and past_key_values(cache)
  paddlenlp/transformers/reformer/modeling.py
  tests/transformers/reformer/test_modeling.py
Labels: contributor, status: proposed

#5210 [ErnieDoc P0] add PretrainedConfig and unit test
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/ernie_doc/configuration.py
  paddlenlp/transformers/ernie_doc/modeling.py
  paddlenlp/transformers/ernie_doc/tokenizer.py
  tests/transformers/ernie_doc/__init__.py
  tests/transformers/ernie_doc/test_modeling.py
  tests/transformers/ernie_doc/test_tokenizer.py
Labels: contributor, status: proposed

#5218 [CI] fix faster transformer
  scripts/regression/ci_case.sh
Labels: contributor, status: proposed

#5214 [Reformer BigBird]Add IntegrationTest
  paddlenlp/transformers/bigbird/modeling.py
  tests/transformers/bigbird/test_modeling.py
  tests/transformers/reformer/test_modeling.py
Labels: contributor, status: proposed

#5255 [CI] Fix transformer xl
  scripts/regression/ci_case.sh
Labels: contributor, status: proposed

#5161 [Model Zoo] Refactor Ernie health usage in Model Zoo
  model_zoo/ernie-health/README.md
  model_zoo/ernie-health/cblue/deploy/predictor/infer_classification.py
  model_zoo/ernie-health/cblue/deploy/predictor/infer_ner.py
  model_zoo/ernie-health/cblue/deploy/predictor/infer_spo.py
  model_zoo/ernie-health/cblue/deploy/predictor/predictor.py
  model_zoo/ernie-health/cblue/deploy/serving/simple_serving/client_classification.py
  model_zoo/ernie-health/cblue/deploy/serving/simple_serving/client_ner.py
  model_zoo/ernie-health/cblue/deploy/serving/simple_serving/client_spo.py
  model_zoo/ernie-health/cblue/export_model.py
  model_zoo/ernie-health/cblue/model.py
  model_zoo/ernie-health/cblue/train_classification.py
  model_zoo/ernie-health/cblue/train_ner.py
  model_zoo/ernie-health/cblue/train_spo.py
  model_zoo/ernie-health/cblue/utils.py
  model_zoo/ernie-health/dataset.py
  model_zoo/ernie-health/preprocess.py
  model_zoo/ernie-health/run_pretrain.py
  model_zoo/ernie-health/run_pretrain_trainer.py
  model_zoo/ernie-health/run_trainer.sh
  paddlenlp/trainer/trainer.py
  paddlenlp/transformers/electra/modeling.py
  tests/fixtures/model_zoo/ernie-health.yaml
  tests/model_zoo/test_ernie-health.py
Labels: contributor, status: proposed

#5251 [Paddle-pipelines] Fix ContentTypes missing bug and upgrade to 0.5.1
  pipelines/VERSION
  pipelines/pipelines/nodes/retriever/dense.py
  pipelines/pipelines/nodes/retriever/sparse.py
  pipelines/requirements.txt
Labels: pipelines

#5272 [Neural Search]Add ClipGradByGlobalNorm for fixing nonconvergence
  applications/neural_search/recall/in_batch_negative/train_batch_neg.py
Labels: neural-search

#5290 [neural search] flake8 neural search
  applications/neural_search/ranking/cross_encoder/deploy/cpp/http_client.py
  applications/neural_search/ranking/cross_encoder/deploy/cpp/rpc_client.py
  applications/neural_search/ranking/cross_encoder/evaluate.py
  applications/neural_search/ranking/cross_encoder/export_model.py
  applications/neural_search/ranking/cross_encoder/predict.py
  applications/neural_search/ranking/ernie_matching/deploy/cpp/http_client.py
  applications/neural_search/ranking/ernie_matching/deploy/cpp/rpc_client.py
  applications/neural_search/ranking/ernie_matching/deploy/python/web_service.py
  applications/neural_search/ranking/ernie_matching/evaluate.py
  applications/neural_search/ranking/ernie_matching/export_model.py
  applications/neural_search/ranking/ernie_matching/predict_pairwise.py
  applications/neural_search/ranking/ernie_matching/train_pairwise.py
  applications/neural_search/recall/in_batch_negative/batch_negative/model.py
  applications/neural_search/recall/in_batch_negative/deploy/cpp/http_client.py
  applications/neural_search/recall/in_batch_negative/deploy/cpp/rpc_client.py
  applications/neural_search/recall/in_batch_negative/deploy/python/predict.py
  applications/neural_search/recall/in_batch_negative/deploy/python/web_service.py
  applications/neural_search/recall/in_batch_negative/export_model.py
  applications/neural_search/recall/in_batch_negative/predict.py
  applications/neural_search/recall/in_batch_negative/recall.py
  applications/neural_search/recall/milvus/feature_extract.py
  applications/neural_search/recall/milvus/inference.py
  applications/neural_search/recall/milvus/milvus_ann_search.py
  applications/neural_search/recall/milvus/milvus_util.py
  applications/neural_search/recall/simcse/data.py
  applications/neural_search/recall/simcse/deploy/python/predict.py
  applications/neural_search/recall/simcse/evaluate.py
  applications/neural_search/recall/simcse/export_model.py
  applications/neural_search/recall/simcse/inference.py
  applications/neural_search/recall/simcse/predict.py
  applications/neural_search/recall/simcse/recall.py
  applications/neural_search/recall/simcse/train.py
  applications/neural_search/run_system.py
Labels: neural-search

#5234 CodeGen examples update
  examples/code_generation/codegen/README.md
  examples/code_generation/codegen/run_clm.py
  examples/code_generation/codegen/run_clm.sh
Labels: contributor, status: proposed

#5159 Add LLaMA
  examples/language_model/llama/README.md
  examples/language_model/llama/args.py
  examples/language_model/llama/configuration.py
  examples/language_model/llama/convert_llama_weights_to_pd.py
  examples/language_model/llama/data.py
  examples/language_model/llama/export_generation_model.py
  examples/language_model/llama/finetune_generation.py
  examples/language_model/llama/infer_generation.py
  examples/language_model/llama/model_split_merge.py
  examples/language_model/llama/modeling.py
  examples/language_model/llama/tokenizer.py
  examples/language_model/llama/utils.py
  examples/language_model/llama/zero_shot_infer.py
Labels: transformers

#5374 fix ernie-1.0 static
  model_zoo/ernie-1.0/run_pretrain_static.py
Labels: contributor, status: proposed

#5376 [CI] fix examples api names bug
  scripts/regression/ci_case.sh
  scripts/regression/run_ci.sh
Labels: contributor, status: proposed

#5385 [Paddle-pipelines] Fix queries_type bugs
  pipelines/VERSION
  pipelines/examples/image_text_retrieval/IMAGE_TO_TEXT_SEARCH.md
  pipelines/examples/image_text_retrieval/README.md
  pipelines/pipelines/nodes/retriever/base.py
  pipelines/pipelines/nodes/retriever/dense.py
  pipelines/pipelines/nodes/retriever/embedder.py
  pipelines/pipelines/nodes/retriever/multimodal_retriever.py
  pipelines/pipelines/pipelines/base.py
Labels: pipelines

#5392 Update roformer config
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/roformer/configuration.py
  paddlenlp/transformers/roformer/modeling.py
  tests/transformers/roformer/test_modeling.py
Labels: contributor, status: proposed

#5225 删除TaskFlow中文生图的文档
  README.md
  docs/model_zoo/taskflow.md
Labels: contributor, status: proposed

#5403 [CI] Fix question matching
  scripts/regression/ci_case.sh
Labels: contributor, status: proposed

#5419 [Typo] Update README.md
  applications/zero_shot_text_classification/README.md
Labels: contributor, status: proposed

#5428 [Typo] Update README.md
  model_zoo/uie/README.md
Labels: contributor, status: proposed

#5423 [Blenderbotsmall P0]add PretrainedConfig and unit test
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/blenderbot_small/configuration.py
  paddlenlp/transformers/blenderbot_small/modeling.py
  paddlenlp/transformers/blenderbot_small/tokenizer.py
  tests/transformers/blenderbot_small/__init__.py
  tests/transformers/blenderbot_small/test_modeling.py
  tests/transformers/blenderbot_small/test_tokenizer.py
Labels: contributor, status: proposed

#5435 [Benchmark] update ernie3.0 benchmark seqlen=5112
  tests/test_tipc/benchmark/modules/ernie3_for_sequence_classification.py
  tests/test_tipc/configs/ernie3_for_sequence_classification/train_infer_python.txt
Labels: contributor, status: proposed

#5445 ctrl add config & test p0 & fix modeling bug
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/ctrl/configuration.py
  paddlenlp/transformers/ctrl/modeling.py
  tests/transformers/ctrl/__init__.py
  tests/transformers/ctrl/test_modeling.py
  tests/transformers/ctrl/test_tokenizer.py
Labels: contributor, status: proposed

#5439 [MPNet P0] Add mpnet test and configuration
  examples/language_model/mpnet/README.md
  examples/language_model/mpnet/glue/run_glue.py
  examples/language_model/mpnet/glue/train.sh
  examples/language_model/mpnet/squad/args.py
  examples/language_model/mpnet/squad/run_squad.py
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/mpnet/configuration.py
  paddlenlp/transformers/mpnet/modeling.py
  paddlenlp/transformers/mpnet/tokenizer.py
  tests/transformers/mpnet/__init__.py
  tests/transformers/mpnet/test_modeling.py
  tests/transformers/mpnet/test_tokenizer.py
  tests/transformers/test_tokenizer_common.py
Labels: contributor, status: proposed

#5465 change ---tokenizer_name to --tokenizer_name
  examples/language_model/roberta/README.md
Labels: contributor, status: proposed

#5485 [Benchmark] update freeze_params
  tests/test_tipc/benchmark/modules/stablediffusion.py
Labels: contributor, status: proposed
