Repository PaddlePaddle/PaddleNLP, pull requests merged in 2023-02, with the labels that each got.

#4616 Fix the pegasus decoder attention mask bug
  paddlenlp/transformers/pegasus/modeling.py
Labels: contributor, status: proposed

#4646 fix args bug in SSTIA
  applications/text_summarization/pegasus/train.py
Labels: contributor, status: proposed

#4619 [Benchmark] add G0 ernie3.0 cls benchmark
  tests/test_tipc/benchmark/modules/bert_for_question_answering.py
  tests/test_tipc/benchmark/modules/ernie3_for_sequence_classification.py
  tests/test_tipc/benchmark/options.py
  tests/test_tipc/configs/ernie-3.0_for_sequence_classification/train_infer_python.txt
Labels: contributor, status: proposed

#4638 Fix pegasus decoder attention mask
  paddlenlp/transformers/pegasus/modeling.py
Labels: contributor, status: proposed

#4654 [Benchmark] Update gpt/bert/t5 optimizer
  tests/test_tipc/benchmark/modules/ernie3_for_sequence_classification.py
  tests/test_tipc/configs/bert_for_question_answering/train_infer_python.txt
  tests/test_tipc/configs/gpt_for_sequence_classification/train_infer_python.txt
  tests/test_tipc/configs/t5_for_conditional_generation/train_infer_python.txt
Labels: contributor, status: proposed

#4695 Add pretrained pegasus and Refactor text summarization
  applications/text_summarization/README.md
  applications/text_summarization/finetune/README.md
  applications/text_summarization/finetune/deploy/paddle_inference/README.md
  applications/text_summarization/finetune/deploy/paddle_inference/inference_pegasus.py
  applications/text_summarization/finetune/deploy/paddle_serving/README.md
  applications/text_summarization/finetune/deploy/paddle_serving/config.yml
  applications/text_summarization/finetune/deploy/paddle_serving/export_serving.sh
  applications/text_summarization/finetune/deploy/paddle_serving/pipeline_client.py
  applications/text_summarization/finetune/deploy/paddle_serving/pipeline_service.py
  applications/text_summarization/finetune/export_model.py
  applications/text_summarization/finetune/export_model.sh
  applications/text_summarization/finetune/predict.py
  applications/text_summarization/finetune/requirements.txt
  applications/text_summarization/finetune/run_prepare.py
  applications/text_summarization/finetune/train.py
  applications/text_summarization/finetune/utils.py
  applications/text_summarization/pretrain/README.md
  applications/text_summarization/pretrain/requirements.txt
  applications/text_summarization/pretrain/train.py
  applications/text_summarization/pretrain/utils.py
  examples/text_summarization/unimo-text/README.md
  examples/text_summarization/unimo-text/deploy/paddle_inference/README.md
  examples/text_summarization/unimo-text/deploy/paddle_inference/inference_unimo_text.py
  examples/text_summarization/unimo-text/deploy/paddle_serving/README.md
  examples/text_summarization/unimo-text/deploy/paddle_serving/config.yml
  examples/text_summarization/unimo-text/deploy/paddle_serving/export_serving.sh
  examples/text_summarization/unimo-text/deploy/paddle_serving/pipeline_client.py
  examples/text_summarization/unimo-text/deploy/paddle_serving/pipeline_service.py
  examples/text_summarization/unimo-text/export_model.py
  examples/text_summarization/unimo-text/export_model.sh
  examples/text_summarization/unimo-text/train.py
  examples/text_summarization/unimo-text/train.sh
  examples/text_summarization/unimo-text/utils.py
Labels: contributor, status: proposed

#4707 update bert and erinie3.0 benchmark
  tests/test_tipc/configs/bert_for_question_answering/train_infer_python.txt
  tests/test_tipc/configs/ernie-3.0_for_sequence_classification/train_infer_python.txt
Labels: contributor, status: proposed

#4706 fix paddlenlp install
  scripts/regression/run_ci.sh
Labels: contributor, status: proposed

#4683 [ChineseBert P0] PretrainedConfig and model unit test
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/bert/modeling.py
  paddlenlp/transformers/chinesebert/configuration.py
  paddlenlp/transformers/chinesebert/modeling.py
  tests/transformers/chinesebert/__init__.py
  tests/transformers/chinesebert/test_modeling.py
Labels: transformers_upgrade

#4722 Fix paddlenlp install
  scripts/regression/run_ci.sh
Labels: contributor, status: proposed

#4720 Use SimpleServing in text_summarization
  applications/text_summarization/finetune/README.md
  applications/text_summarization/finetune/deploy/paddle_serving/README.md
  applications/text_summarization/finetune/deploy/paddle_serving/config.yml
  applications/text_summarization/finetune/deploy/paddle_serving/pipeline_client.py
  applications/text_summarization/finetune/deploy/paddle_serving/pipeline_service.py
  applications/text_summarization/finetune/deploy/simple_serving/README.md
  applications/text_summarization/finetune/deploy/simple_serving/client.py
  applications/text_summarization/finetune/deploy/simple_serving/server.py
Labels: contributor, status: proposed

#4729 ci add lexical_analysis
  scripts/regression/run_ci.sh
Labels: contributor, status: proposed

#4676 [NEW Model] Add BLIP Model & CLIP Interrogator
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/auto/modeling.py
  paddlenlp/transformers/blip/__init__.py
  paddlenlp/transformers/blip/configuration.py
  paddlenlp/transformers/blip/image_processing.py
  paddlenlp/transformers/blip/modeling.py
  paddlenlp/transformers/blip/modeling_text.py
  paddlenlp/transformers/blip/processing.py
  paddlenlp/transformers/image_processing_utils.py
  ppdiffusers/examples/clip_interrogator/LICENSE
  ppdiffusers/examples/clip_interrogator/README.md
  ppdiffusers/examples/clip_interrogator/clip_interrogator/__init__.py
  ppdiffusers/examples/clip_interrogator/clip_interrogator/blip_decoder.py
  ppdiffusers/examples/clip_interrogator/clip_interrogator/clip_interrogator.py
  ppdiffusers/examples/clip_interrogator/dumpy.py
  ppdiffusers/examples/clip_interrogator/predict.py
  ppdiffusers/examples/clip_interrogator/requirements.txt
  ppdiffusers/examples/clip_interrogator/run_cli.py
  ppdiffusers/examples/clip_interrogator/run_gradio.py
  tests/transformers/blip/__init__.py
  tests/transformers/blip/test_modeling.py
  tests/transformers/blip/test_modeling_text.py
  tests/transformers/blip/test_processor.py
Labels: contributor, status: proposed

#4735 Fix unimo-text shell typo
  examples/text_summarization/unimo-text/README.md
  examples/text_summarization/unimo-text/train.py
  examples/text_summarization/unimo-text/train.sh
Labels: contributor, status: proposed

#4751 [Benchmark] enable ernie3.0 benchmark
  tests/test_tipc/benchmark/modules/ernie3_for_sequence_classification.py
  tests/test_tipc/benchmark/options.py
  tests/test_tipc/configs/ernie3_for_sequence_classification/train_infer_python.txt
Labels: contributor, status: proposed

#4769 update text classification taskflow
  paddlenlp/experimental/autonlp/text_classification.py
  paddlenlp/taskflow/taskflow.py
  paddlenlp/taskflow/text_classification.py
  tests/taskflow/test_text_classification.py
Labels: taskflow, text classification

#4774 [autonlp] text classification bug fix
  paddlenlp/experimental/autonlp/auto_trainer_base.py
  paddlenlp/experimental/autonlp/text_classification.py
  tests/experimental/autonlp/test_text_classification.py
Labels: autonlp

#4626 [T5] Add clue finetune scripts of trainer
  examples/language_model/t5/README.md
  examples/language_model/t5/data.py
  examples/language_model/t5/run_clue_trainer.py
  examples/language_model/t5/utils.py
  paddlenlp/trainer/trainer.py
  paddlenlp/trainer/trainer_seq2seq.py
  paddlenlp/transformers/t5/modeling.py
Labels: contributor, status: proposed

#4797 CLIP, ErnieViL, ChineseCLIP Remove from_pretrained_v2
  paddlenlp/transformers/chineseclip/modeling.py
  paddlenlp/transformers/clip/modeling.py
  paddlenlp/transformers/ernie_vil/modeling.py
Labels: contributor, status: proposed

#4803 [PretrainedConfig]set ensure_ascii to False
  paddlenlp/transformers/configuration_utils.py
Labels: transformers

#4804 unify id2label key type
  paddlenlp/taskflow/text_classification.py
Labels: taskflow

#4795 enhancement: add simpleServing code for sentence transformers
  examples/text_matching/sentence_transformers/deploy/simple_serving/README.md
  examples/text_matching/sentence_transformers/deploy/simple_serving/client.py
  examples/text_matching/sentence_transformers/deploy/simple_serving/server.py
  examples/text_matching/sentence_transformers/export_model.py
Labels: contributor, status: proposed

#4829 fix: mt5 init
  paddlenlp/transformers/mt5/__init__.py
Labels: contributor, status: proposed

#4810 update text classification application
  applications/text_classification/multi_class/README.md
  applications/text_classification/multi_class/analysis/README.md
  applications/text_classification/multi_class/analysis/evaluate.py
  applications/text_classification/multi_class/deploy/paddle_serving/README.md
  applications/text_classification/multi_class/deploy/paddle_serving/config.yml
  applications/text_classification/multi_class/deploy/paddle_serving/http_client.py
  applications/text_classification/multi_class/deploy/paddle_serving/rpc_client.py
  applications/text_classification/multi_class/deploy/paddle_serving/service.py
  applications/text_classification/multi_class/deploy/predictor/README.md
  applications/text_classification/multi_class/deploy/predictor/infer.py
  applications/text_classification/multi_class/deploy/predictor/predictor.py
  applications/text_classification/multi_class/deploy/simple_serving/README.md
  applications/text_classification/multi_class/deploy/simple_serving/client.py
  applications/text_classification/multi_class/deploy/simple_serving/ernie_m_server.py
  applications/text_classification/multi_class/deploy/simple_serving/server.py
  applications/text_classification/multi_class/deploy/triton_serving/README.md
  applications/text_classification/multi_class/export_model.py
  applications/text_classification/multi_class/predict.py
  applications/text_classification/multi_class/prune.py
  applications/text_classification/multi_class/train.py
  applications/text_classification/multi_class/utils.py
Labels: text classification

#4749 [Benchmark] enable bert benchmark
  tests/test_tipc/configs/bert_for_question_answering/train_infer_python.txt
Labels: contributor, status: proposed

#4815 [autonlp] add text classifcation taskflow
  paddlenlp/experimental/autonlp/auto_trainer_base.py
  paddlenlp/experimental/autonlp/text_classification.py
  paddlenlp/taskflow/text_classification.py
  tests/experimental/autonlp/test_text_classification.py
Labels: autonlp

#4865 [autonlp]add new test for text classifictaion
  paddlenlp/experimental/autonlp/text_classification.py
  tests/experimental/autonlp/test_text_classification.py
Labels: autonlp

#4868 [CI] add ernie-layout & uie
  scripts/regression/ci_case.sh
  scripts/regression/run_release.sh
Labels: contributor, status: proposed

#4830 [PPDiffusers] add_cycle_diffusion_space
  ppdiffusers/examples/Stable-CycleDiffusion/README.md
  ppdiffusers/examples/Stable-CycleDiffusion/app.py
  ppdiffusers/examples/Stable-CycleDiffusion/ptp_utils.py
  ppdiffusers/examples/Stable-CycleDiffusion/requirements.txt
  ppdiffusers/examples/Stable-CycleDiffusion/seq_aligner.py
  ppdiffusers/examples/text_to_image/README.md
  ppdiffusers/ppdiffusers/pipelines/stable_diffusion/pipeline_cycle_diffusion.py
Labels: contributor, status: proposed

#4884 Fix mt5 test
  tests/transformers/mt5/test_modeling.py
Labels: contributor, status: proposed

#4893 [CI] Change ernie-1.0 to ernie-1.0-base-zh
  scripts/regression/ci_case.sh
Labels: contributor, status: proposed

#4894 [PPDiffusers] add lora rank option
  ppdiffusers/examples/dreambooth/train_dreambooth_lora.py
  ppdiffusers/ppdiffusers/models/cross_attention.py
  ppdiffusers/scripts/convert_diffusers_model/convert_orig_sd_ckpt_to_ppdiffusers.py
Labels: contributor, status: proposed

#4890 fix: fix issue #4801
  applications/document_intelligence/doc_vqa/OCR_process/ocr_process.py
Labels: contributor, status: proposed

#4902 Fix pipelines install
  scripts/regression/ci_case.sh
  scripts/regression/run_ci.sh
Labels: contributor, status: proposed

#4896 [autonlp] text classification fix& add taskflow config file
  paddlenlp/experimental/autonlp/auto_trainer_base.py
  paddlenlp/experimental/autonlp/text_classification.py
  tests/experimental/autonlp/test_text_classification.py
Labels: text classification, autonlp

#4906 fix 4903
  model_zoo/bert/README.md
  model_zoo/bert/run_pretrain.py
Labels: contributor, status: proposed

#4918 Update README.md
  applications/information_extraction/document/README.md
  applications/information_extraction/document/README_en.md
  applications/information_extraction/document/deploy/simple_serving/README.md
  applications/information_extraction/document/deploy/simple_serving/README_en.md
  applications/information_extraction/text/data_distill/deploy/simple_serving/README.md
  applications/information_extraction/text/data_distill/deploy/simple_serving/README_en.md
  applications/information_extraction/text/deploy/simple_serving/README.md
  applications/information_extraction/text/deploy/simple_serving/README_en.md
  model_zoo/uie/deploy/serving/simple_serving/README.md
Labels: contributor, status: proposed

#4930 [Trainer] add dp_group and exclude_layer params
  paddlenlp/trainer/trainer.py
Labels: contributor, status: proposed

#4925 [PPDiffusers] Update lora rank
  ppdiffusers/examples/dreambooth/README.md
  ppdiffusers/examples/dreambooth/train_dreambooth_lora.py
  ppdiffusers/examples/text_to_image/README.md
  ppdiffusers/examples/text_to_image/train_text_to_image_lora.py
Labels: contributor, status: proposed

#4959 Fix typos
  docs/get_started/installation.rst
  docs/locale/en/LC_MESSAGES/get_started/installation.po
  docs/model_zoo/embeddings.md
  examples/text_to_sql/IGSQL/README.md
  examples/text_to_sql/RAT-SQL/evaluation/README.md
  examples/text_to_sql/RAT-SQL/text2sql/dataproc/ernie_input_encoder_v2.py
  examples/text_to_sql/RAT-SQL/text2sql/dataproc/sql_preproc_v2.py
  examples/text_to_sql/RAT-SQL/text2sql/io.py
  examples/text_to_sql/RAT-SQL/text2sql/models/sql_beam_search.py
  examples/text_to_sql/RAT-SQL/text2sql/optim.py
  examples/text_to_sql/RAT-SQL/text2sql/utils/dusql_evaluation.py
  examples/text_to_sql/RAT-SQL/text2sql/utils/nn_utils.py
  examples/text_to_sql/RAT-SQL/text2sql/utils/text_utils.py
  examples/text_to_sql/RAT-SQL/text2sql/utils/utils.py
  examples/word_embedding/train.py
  paddlenlp/ops/einsum.py
  paddlenlp/prompt/prompt_utils.py
  paddlenlp/prompt/template.py
  paddlenlp/seq2vec/encoder.py
  paddlenlp/taskflow/dependency_parsing.py
  paddlenlp/taskflow/models/dependency_parsing_model.py
  paddlenlp/taskflow/models/sentiment_analysis_model.py
  paddlenlp/taskflow/models/text_correction_model.py
Labels: contributor, status: proposed

#4912 [MegatronBERT P0] add PretrainedConfig and unit test
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/megatronbert/configuration.py
  paddlenlp/transformers/megatronbert/modeling.py
  paddlenlp/transformers/megatronbert/tokenizer.py
  tests/transformers/megatronbert/__init__.py
  tests/transformers/megatronbert/test_modeling.py
  tests/transformers/megatronbert/test_tokenizer.py
Labels: hackathon, contributor, status: proposed

#4986 fix static gpt3 generation attention_mask
  examples/language_model/gpt-3/static/modeling.py
Labels: contributor, status: proposed

#4987 fix: search_fields of pipelines
  pipelines/rest_api/pipeline/multi_recall_semantic_search.yaml
  pipelines/utils/offline_ann.py
Labels: pipelines, contributor, status: not progressed

#4994 Fix typos
  applications/neural_search/ranking/cross_encoder/deploy/python/predict.py
  applications/neural_search/ranking/ernie_matching/deploy/python/predict.py
  applications/neural_search/recall/in_batch_negative/deploy/python/predict.py
  applications/neural_search/recall/milvus/feature_extract.py
  applications/neural_search/recall/simcse/deploy/python/predict.py
  applications/question_answering/supervised_qa/faq_finance/feature_extract.py
  applications/question_answering/supervised_qa/faq_system/feature_extract.py
  applications/sentiment_analysis/ASO_analysis/deploy/predict.py
  applications/text_classification/hierarchical/deploy/triton_serving/models/seqcls_postprocess/1/model.py
  applications/text_classification/hierarchical/deploy/triton_serving/models/tokenizer/1/model.py
  applications/text_classification/hierarchical/retrieval_based/deploy/python/predict.py
  applications/text_classification/hierarchical/retrieval_based/utils/feature_extract.py
  applications/text_classification/multi_class/deploy/triton_serving/models/seqcls_postprocess/1/model.py
  applications/text_classification/multi_class/deploy/triton_serving/models/tokenizer/1/model.py
  applications/text_classification/multi_class/retrieval_based/data.py
  applications/text_classification/multi_class/retrieval_based/deploy/python/predict.py
  applications/text_classification/multi_class/retrieval_based/evaluate.py
  applications/text_classification/multi_class/retrieval_based/model.py
  applications/text_classification/multi_class/retrieval_based/train.py
  applications/text_classification/multi_class/retrieval_based/utils/feature_extract.py
  applications/text_classification/multi_label/deploy/triton_serving/models/seqcls_postprocess/1/model.py
  applications/text_classification/multi_label/deploy/triton_serving/models/tokenizer/1/model.py
  applications/text_classification/multi_label/retrieval_based/deploy/python/predict.py
  applications/text_classification/multi_label/retrieval_based/utils/feature_extract.py
  examples/information_extraction/waybill_ie/deploy/python/predict_bigru_crf.py
  examples/information_extraction/waybill_ie/deploy/python/predict_ernie.py
  examples/information_extraction/waybill_ie/deploy/python/predict_ernie_crf.py
  examples/text_matching/ernie_matching/deploy/python/predict.py
  model_zoo/ernie-1.0/finetune/deploy/predict_chnsenticorp.py
  model_zoo/ernie-3.0/deploy/serving/models/ernie_seqcls_postprocess/1/model.py
  model_zoo/ernie-3.0/deploy/serving/models/ernie_seqcls_tokenizer/1/model.py
  model_zoo/ernie-3.0/deploy/serving/models/ernie_tokencls_postprocess/1/model.py
  model_zoo/ernie-3.0/deploy/serving/models/ernie_tokencls_tokenizer/1/model.py
  paddlenlp/data/sampler.py
  tests/test_tipc/ernie_information_extraction/predict.py
  tests/test_tipc/ernie_text_cls/predict.py
  tests/test_tipc/ernie_text_matching/predict.py
Labels: contributor, status: proposed

#4961 [BigBird P0] Add PretrainedConfig and unit tests
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/bigbird/configuration.py
  paddlenlp/transformers/bigbird/modeling.py
  paddlenlp/transformers/bigbird/tokenizer.py
  tests/transformers/bigbird/__init__.py
  tests/transformers/bigbird/test_modeling.py
  tests/transformers/bigbird/test_tokenizer.py
Labels: contributor, status: proposed

#5006 [neural search] change expit to softmax
  applications/neural_search/ranking/cross_encoder/deploy/python/predict.py
  applications/neural_search/ranking/cross_encoder/deploy/python/web_service.py
Labels: neural-search
