Repository PaddlePaddle/PaddleNLP, pull requests merged in 2024-10, with the labels that each got.

#9258 [Tokenizer] Enable padding_side as call time kwargs
  paddlenlp/transformers/artist/tokenizer.py
  paddlenlp/transformers/bloom/tokenizer.py
  paddlenlp/transformers/chatglm/tokenizer.py
  paddlenlp/transformers/chatglm_v2/tokenizer.py
  paddlenlp/transformers/dallebart/tokenizer.py
  paddlenlp/transformers/gemma/tokenizer.py
  paddlenlp/transformers/gpt/tokenizer.py
  paddlenlp/transformers/llama/tokenizer.py
  paddlenlp/transformers/mamba/tokenizer.py
  paddlenlp/transformers/qwen/tokenizer.py
  paddlenlp/transformers/tokenizer_utils.py
  paddlenlp/transformers/tokenizer_utils_base.py
  paddlenlp/transformers/tokenizer_utils_fast.py
  tests/transformers/chatglm/test_tokenizer.py
  tests/transformers/test_tokenizer_common.py
Labels: contributor

#9304 [Tokenizer] Fix TokenizerFast missing clean_up_tokenization_spaces
  paddlenlp/transformers/tokenizer_utils_base.py
Labels: XPU

#9312 [XPU] support unified ckpt function
  paddlenlp/trainer/plugins/unified_checkpoint.py
  paddlenlp/trainer/trainer.py
Labels: XPU

#9186 [METAX] Support llama for MX C550
  llm/metax/llama/README.md
Labels: 多硬件

#9215 [Tokenizer] Support reading Tiktoken tokenizer.model.
  paddlenlp/transformers/albert/__init__.py
  paddlenlp/transformers/albert/tokenizer.py
  paddlenlp/transformers/auto/configuration.py
  paddlenlp/transformers/auto/factory.py
  paddlenlp/transformers/auto/tokenizer.py
  paddlenlp/transformers/configuration_utils.py
  paddlenlp/transformers/convert_slow_tokenizer.py
  paddlenlp/transformers/ernie/__init__.py
  paddlenlp/transformers/llama/tokenizer.py
  paddlenlp/transformers/llama/tokenizer_fast.py
  paddlenlp/transformers/mbart/__init__.py
  paddlenlp/transformers/tokenizer_utils_base.py
  paddlenlp/transformers/tokenizer_utils_fast.py
  paddlenlp/utils/__init__.py
  paddlenlp/utils/env.py
  paddlenlp/utils/import_utils.py
  requirements.txt
  tests/transformers/auto/test_confiugration.py
  tests/transformers/llama/test_tokenizer.py
Labels: contributor
