Repository PaddlePaddle/PaddleNLP, pull requests merged in 2024-11, with the labels that each got.

#9353 [Tokenizer] Add BertTokenizerFast, support register new tokenizer
  paddlenlp/transformers/auto/tokenizer.py
  paddlenlp/transformers/bert/tokenizer_fast.py
  paddlenlp/transformers/convert_slow_tokenizer.py
  paddlenlp/transformers/tokenizer_utils_base.py
  paddlenlp/transformers/tokenizer_utils_fast.py
  tests/transformers/auto/test_confiugration.py
  tests/transformers/auto/test_tokenizer.py
  tests/transformers/bert/test_tokenizer.py
  tests/transformers/test_tokenizer_common.py
  tests/utils/test_module/__init__.py
  tests/utils/test_module/custom_configuration.py
  tests/utils/test_module/custom_tokenizer.py
  tests/utils/test_module/custom_tokenizer_fast.py
Labels: contributor

#9373 Support pp + no_recompute_layer.
  paddlenlp/transformers/llama/modeling_pp.py
Labels: contributor

#9389 [CI] add recursive for submodule
  scripts/regression/run_ci.sh
Labels: contributor

#9394 [CI]fix scripts
  scripts/regression/run_ci.sh
Labels: contributor

#9414 [XPU] Llama XPU's swiglu uses phi's swiglu
  paddlenlp/transformers/llama/modeling.py
Labels: XPU

#9404 [fix] shard-reshard下dp间is_matched行为不一致，以dp0为准
  paddlenlp/trainer/utils/sharding_io.py
Labels: contributor

#9416 [INFER][LLM] Add the AutoModel for inference mode
  llm/predict/predictor.py
  paddlenlp/experimental/transformers/bloom/modeling.py
  paddlenlp/experimental/transformers/llama/modeling.py
  paddlenlp/transformers/auto/modeling.py
  paddlenlp/transformers/chatglm_v2/modeling.py
  paddlenlp/transformers/model_utils.py
Labels: contributor

#9434 Change core.LoDTensor to core.DenseTensor
  slm/model_zoo/bert/static_ipu/dataset_ipu.py
Labels: contributor

#9419 Change LOD_TENSOR to DENSE_TENSOR
  slm/model_zoo/gpt-3/ppfleetx/optims/optimizer.py
Labels: contributor

#9432 [AutoParallel] add release_gradients and comm_buffer_size_MB to strategy
  paddlenlp/trainer/training_args.py
Labels: contributor

#9382 [AutoParallel] Reconstruct sharding mesh dimension inference logic - Part2 add sharding_mesh_dimension param
  paddlenlp/trainer/auto_trainer.py
  paddlenlp/trainer/training_args.py
Labels: contributor

#9462 [ChatTemplate] Fix chat template for `Gemma` when answer is contained within question.
  paddlenlp/transformers/gemma/tokenizer.py
  tests/transformers/gemma/test_tokenizer.py
Labels: contributor

#9331 add Moslora
  llm/docs/finetune.md
  llm/run_finetune.py
  llm/tools/merge_lora_params.py
  llm/utils/argument.py
  paddlenlp/peft/lora/lora_config.py
  paddlenlp/peft/lora/lora_layers.py
  paddlenlp/peft/lora/lora_model.py
  tests/fixtures/llm/mos_lora.yaml
  tests/llm/test_mos_lora.py
  tests/peft/test_mos_lora.py
Labels: Beijing Innovation Consortium

#9481 [AutoParallel] Fix parameter passing for comm_buffer_size_MB and release_gradients
  paddlenlp/trainer/training_args.py
Labels: contributor

#9476 fixbug for chatglm_v2's RetaryEmbedding dtype
  paddlenlp/transformers/chatglm_v2/modeling.py
Labels: contributor

#9180 [LLM INFER] Support speculative decoding (llama)
  csrc/cpu/src/stop_generation_multi_ends.cc
  csrc/gpu/get_output.cc
  csrc/gpu/get_padding_offset_v2.cu
  csrc/gpu/helper.h
  csrc/gpu/rebuild_padding_v2.cu
  csrc/gpu/save_with_output_msg.cc
  csrc/gpu/speculate_decoding_kernels/ngram_match.cc
  csrc/gpu/speculate_decoding_kernels/speculate_get_output_padding_offset.cu
  csrc/gpu/speculate_decoding_kernels/speculate_get_seq_lens_output.cu
  csrc/gpu/speculate_decoding_kernels/speculate_set_value_by_flags.cu
  csrc/gpu/speculate_decoding_kernels/speculate_step.cu
  csrc/gpu/speculate_decoding_kernels/speculate_verify_and_update.cu
  csrc/gpu/speculate_decoding_kernels/top_p_candidates.cu
  csrc/gpu/stop_generation_multi_ends.cu
  csrc/gpu/unittest/test_get_padding_offset_v2.py
  csrc/setup_cuda.py
  llm/predict/export_model.py
  llm/predict/predictor.py
  paddlenlp/experimental/transformers/__init__.py
  paddlenlp/experimental/transformers/bloom/modeling.py
  paddlenlp/experimental/transformers/chatglm_v2/modeling.py
  paddlenlp/experimental/transformers/fused_transformer_layers.py
  paddlenlp/experimental/transformers/generation_utils.py
  paddlenlp/experimental/transformers/llama/modeling.py
  paddlenlp/experimental/transformers/mixtral/modeling.py
  paddlenlp/experimental/transformers/proposers.py
  paddlenlp/experimental/transformers/qwen2/modeling.py
  paddlenlp/experimental/transformers/qwen2_moe/modeling.py
  paddlenlp/transformers/auto/modeling.py
  paddlenlp/transformers/model_utils.py
  paddlenlp/trl/llm_utils.py
  paddlenlp/utils/env.py
  tests/llm/test_speculate_decoding.py
Labels: inference

#9468 [AutoParallel] open vpp test cast at v100 machines
  scripts/distribute/ci_case_auto.sh
Labels: contributor

#9485 [ChatTemplate] Fix chat template for `Yuan` when answer is contained within question.
  paddlenlp/transformers/yuan/tokenizer.py
  tests/transformers/yuan/__init__.py
  tests/transformers/yuan/test_tokenizer.py
Labels: contributor

#9495 [XPU] set appropriate mask value for xpu
  paddlenlp/transformers/llama/modeling.py
Labels: XPU

#9407 【Hackathon 7th No.43】完善 TokenizerFast 功能支持 part 1
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/auto/tokenizer.py
  paddlenlp/transformers/bert/tokenizer_fast.py
  paddlenlp/transformers/bloom/tokenizer_fast.py
  paddlenlp/transformers/convert_slow_tokenizer.py
  tests/transformers/bloom/test_tokenizer.py
Labels: contributor
