Repository PaddlePaddle/PaddleNLP, pull requests merged in 2025-03, with the labels that each got.

#9598 Add Process Reward Model.
  llm/alignment/rm/flashmask/data.py
  llm/alignment/rm/flashmask/reward_argument.py
  llm/alignment/rm/flashmask/reward_model.py
  llm/alignment/rm/flashmask/reward_trainer.py
  llm/alignment/rm/flashmask/run_reward.py
  llm/config/llama/prm_flashmask_argument.json
  llm/config/mistral/prm_flashmask_argument.json
  llm/docs/prm.md
  paddlenlp/transformers/llama/modeling.py
  paddlenlp/transformers/mistral/modeling.py
  tests/fixtures/llm/prm_data/dev.json
  tests/fixtures/llm/prm_data/train.json
  tests/fixtures/llm/prm_flashmask.yaml
  tests/llm/test_prm.py
Labels: contributor

#9848 [Feat] Sage Attention Kernels Support for sm80, sm89, sm90
  csrc/gpu/sage_attn_kernels/sageattn_fused.cu
  csrc/gpu/sage_attn_kernels/sageattn_qk_int_sv_f16_kernel_sm80.cu
  csrc/gpu/sage_attn_kernels/sageattn_qk_int_sv_f8_dsk_kernel_sm90.cu
  csrc/gpu/sage_attn_kernels/sageattn_qk_int_sv_f8_kernel_sm89.cu
  csrc/gpu/sage_attn_kernels/sageattn_qk_int_sv_f8_kernel_sm90.cu
  csrc/gpu/sage_attn_kernels/sageattn_utils.cuh
  csrc/setup_cuda.py
  paddlenlp/experimental/transformers/fused_transformer_layers.py
  paddlenlp/experimental/transformers/sageattention.py
  paddlenlp/utils/env.py
Labels: contributor

#10021 [Performance optimization] Sage Attention Enhancement
  csrc/gpu/sage_attn_kernels/sageattn_fused.cu
  csrc/gpu/sage_attn_kernels/sageattn_fused.cuh
  csrc/gpu/sage_attn_kernels/sageattn_qk_int_sv_f16_kernel_sm80.cu
  csrc/gpu/sage_attn_kernels/sageattn_qk_int_sv_f8_dsk_kernel_sm90.cu
  csrc/gpu/sage_attn_kernels/sageattn_qk_int_sv_f8_kernel_sm89.cu
  csrc/gpu/sage_attn_kernels/sageattn_qk_int_sv_f8_kernel_sm90.cu
  paddlenlp/experimental/transformers/fused_transformer_layers.py
  paddlenlp/experimental/transformers/sageattention.py
Labels: contributor

#10045 [CI]Fix ci scripts
  scripts/distribute/ci_case_auto.sh
  scripts/distribute/run_ci.sh
  scripts/regression/ci_case.sh
  scripts/regression/run_ci.sh
  scripts/unit_test/ci_unit.sh
Labels: contributor

#10000 [LLM] Update GLM
  paddlenlp/transformers/chatglm_v2/configuration.py
  paddlenlp/transformers/chatglm_v2/modeling.py
  paddlenlp/transformers/glm/modeling.py
Labels: contributor

#10054 [CI]fix auto case only in a100
  scripts/distribute/ci_case_auto.sh
Labels: contributor

#10104 [CI]Fix
  scripts/regression/ci_case.sh
  scripts/regression/run_ci.sh
  scripts/unit_test/ci_unit.sh
Labels: contributor

#9933 [Typos] Fix typos
  csrc/cpu/src/avx_weight_only.cc
  csrc/gpu/cutlass_kernels/fp8_gemm_fused/dual_gemm/thread/left_gelu_and_mul.h
  csrc/gpu/cutlass_kernels/fp8_gemm_fused/dual_gemm/thread/left_silu_and_mul.h
  csrc/gpu/cutlass_kernels/fp8_gemm_fused/dual_gemm/threadblock/dual_mma_base.h
  csrc/gpu/dequant_int8.cu
  csrc/gpu/int8_gemm_with_cutlass/epilogue_tensor_op_int32.h
  csrc/gpu/quant_int8.cu
  csrc/gpu/set_preids_token_penalty_multi_scores.cu
  csrc/gpu/set_value_by_flags_v2.cu
  csrc/gpu/speculate_decoding_kernels/speculate_set_value_by_flags.cu
  docs/FAQ.md
  docs/advanced_guide/model_compression/ofa_bert.rst
  docs/llm/docs/llm_trainer.rst
  docs/metrics.md
  docs/metrics/metrics.md
  docs/model_zoo/transformers/BERT/contents.rst
  docs/trainer.md
  llm/docs/quantization.md
  llm/tools/preprocess/README.md
  paddlenlp/cli/main.py
  paddlenlp/data/causal_dataset.py
  paddlenlp/data/dist_dataloader.py
  paddlenlp/dataaug/char.py
  paddlenlp/dataaug/word.py
  paddlenlp/transformers/ernie_vil/configuration.py
  paddlenlp/transformers/ernie_vil/image_processing.py
  paddlenlp/transformers/qwen2_moe/configuration.py
  paddlenlp/transformers/tokenizer_utils.py
Labels: contributor, HappyOpenSource

#9717 docs(compression): section links step list
  docs/compression.md
Labels: contributor, stale, HappyOpenSource

#10141 [Hot Fix] hotfix for param `decoder_chunk_size_cpu ` during LLM inferencing
  paddlenlp/experimental/transformers/fused_transformer_layers.py
Labels: contributor

#10162 [CI] fix install issue for requirements-dev.txt
  requirements-dev.txt
Labels: contributor

#10171 [predict] fix ddp bug for predict benchmark.
  llm/predict/predictor.py
Labels: contributor

#10074 Add XLMRoberta in Embedding Train
  llm/config/xlm_roberta/emb_argument.json
  llm/run_embedding.py
  llm/utils/argument.py
  paddlenlp/data/data_collator.py
  paddlenlp/datasets/embedding_dataset.py
  paddlenlp/transformers/xlm_roberta/modeling.py
Labels: contributor

#10097 Add Contrastive Learning
  slm/examples/README.md
  slm/examples/contrastive_learning/README.md
  slm/examples/contrastive_learning/clean_query.py
  slm/examples/contrastive_learning/embedding_evaluate.py
  slm/examples/contrastive_learning/mining_negative_samples.py
  slm/examples/contrastive_learning/toy_data/toy_dev.json
  slm/examples/contrastive_learning/toy_data/toy_dev_neg.json
  slm/examples/contrastive_learning/toy_data/toy_source.json
Labels: contributor

#10183 [CI]fix bug for deepseek_data & paddleocr2.10_install & paddlenlp_ops whl
  requirements-dev.txt
  scripts/distribute/ci_case_auto.sh
  scripts/regression/ci_case.sh
  scripts/regression/requirements_ci.txt
Labels: contributor

#10135 [CI]update upload for ci
  scripts/regression/build.sh
  scripts/regression/ci_case.sh
  scripts/regression/run_ci.sh
Labels: contributor

#10175 Save config file for inforence in automatic parallel training
  paddlenlp/trainer/auto_trainer.py
Labels: contributor

#9893 [LLM] Add Minimax-Text-01
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/minimax_text_01/__init__.py
  paddlenlp/transformers/minimax_text_01/configuration.py
  paddlenlp/transformers/minimax_text_01/modeling.py
  tests/transformers/minimax_text_01/__init__.py
  tests/transformers/minimax_text_01/test_modeling.py
Labels: contributor

#10115 Fix typos in multiple files
  csrc/gpu/sage_attn_kernels/sageattn_qk_int_sv_f8_kernel_sm89.cu
  csrc/gpu/sage_attn_kernels/sageattn_utils.cuh
  docs/data_prepare/data_preprocess.rst
  docs/data_prepare/dataset_load.rst
  llm/alignment/ppo/infer_utils.py
  llm/alignment/ppo/models/model_pp.py
  llm/alignment/ppo/ppo_trainer.py
  llm/alignment/ppo/tests/run_model.py
  llm/alignment/ppo/trainer_utils.py
  llm/application/information_extraction/doccano.py
  llm/auto_parallel/deepseek-v3/run_pretrain_auto.py
  llm/auto_parallel/gpt-3/run_pretrain_auto.py
  llm/auto_parallel/llama/run_pretrain_auto.py
  llm/auto_parallel/qwen/run_pretrain_auto.py
  llm/auto_parallel/run_finetune_auto.py
  llm/devices/intel_hpu/llama/README.md
  llm/docs/predict/deepseek.md
  llm/experimental/ernie-3.5-se/conversion_utils.py
  llm/experimental/ernie-3.5-se/modeling.py
  llm/experimental/ernie-3.5-se/run_pretrain.py
  llm/run_finetune.py
  llm/run_pretrain.py
  llm/run_quantization.py
  llm/server/docs/deploy_usage_tutorial.md
  llm/tools/preprocess/create_pretraining_data.py
  ops/csrc/selective_scan/selective_scan_bwd_bf16_complex.cu
  ops/csrc/selective_scan/selective_scan_bwd_bf16_real.cu
  ops/csrc/selective_scan/selective_scan_bwd_fp16_complex.cu
  ops/csrc/selective_scan/selective_scan_bwd_fp16_real.cu
  ops/csrc/selective_scan/selective_scan_bwd_fp32_complex.cu
  ops/csrc/selective_scan/selective_scan_bwd_fp32_real.cu
  ops/csrc/selective_scan/selective_scan_fwd_bf16_complex.cu
  ops/csrc/selective_scan/selective_scan_fwd_bf16_real.cu
  ops/csrc/selective_scan/selective_scan_fwd_fp16_complex.cu
  ops/csrc/selective_scan/selective_scan_fwd_fp16_real.cu
  ops/csrc/selective_scan/selective_scan_fwd_fp32_complex.cu
  ops/csrc/selective_scan/selective_scan_fwd_fp32_real.cu
  ops/src/paddlenlp_kernel/triton/mamba/layer_norm.py
  ops/tests/triton/cut_cross_entropy/test_cce_lse.py
  paddlenlp/dataaug/sentence.py
  paddlenlp/experimental/autonlp/text_classification.py
  paddlenlp/experimental/transformers/llama/modeling.py
  paddlenlp/experimental/transformers/mixtral/modeling.py
  paddlenlp/experimental/transformers/opt/modeling.py
  paddlenlp/mergekit/merge_method.py
  paddlenlp/mergekit/sparsify_method.py
  paddlenlp/prompt/template.py
  paddlenlp/server/http_router/router.py
Labels: contributor

#9887 [Embedding] Add LLARA-passage and bge-en-icl with benchmark
  paddlenlp/transformers/__init__.py
  paddlenlp/transformers/llm_embed/modeling.py
  paddlenlp/transformers/nv_embed/modeling.py
  slm/pipelines/examples/contrastive_training/README.md
  slm/pipelines/examples/contrastive_training/evaluation/eval_mteb.py
  slm/pipelines/examples/contrastive_training/evaluation/eval_mteb.sh
  slm/pipelines/examples/contrastive_training/models/__init__.py
  slm/pipelines/examples/contrastive_training/models/modeling.py
  slm/pipelines/examples/contrastive_training/models/modeling_nv.py
  slm/pipelines/examples/contrastive_training/requirements.txt
  tests/transformers/llm_embed/test_modeling.py
Labels: contributor, Beijing Innovation Consortium
