Repository PaddlePaddle/PaddleNLP, pull requests merged in 2025-09, with the labels that each got.

#11054 [CI]fix no data for dist
  scripts/distribute/ci_case_dy.sh
Labels: contributor

#9776 LoriKiT
  llm/docs/finetune.md
  llm/run_finetune.py
  llm/tools/merge_lora_params.py
  paddlenlp/peft/lora/lora_config.py
  paddlenlp/peft/lora/lora_layers.py
  paddlenlp/peft/lora/lora_model.py
  paddlenlp/trl/model_config.py
  tests/fixtures/llm/linchain.yaml
  tests/llm/test_linchain.py
  tests/peft/test_linchain.py
Labels: Beijing Innovation Consortium

#11079 [cherry-pick] add zcc_ema_loss_threshold args to avoid merging models…
  paddlenlp/trainer/trainer.py
  paddlenlp/trainer/training_args.py
  paddlenlp/trainer/utils/zero_cost_checkpoint.py
Labels: contributor

#11059 Make sharding_first by default
  paddlenlp/trainer/training_args.py
  scripts/distribute/ci_case_auto.sh
  scripts/distribute/run_ci.sh
Labels: skip-ci: distribute-a100, skip-ci: distribute-v100

#11065 Pr adapt flex checkpoint
  paddlenlp/trainer/trainer.py
  paddlenlp/trainer/trainer_utils.py
  paddlenlp/trainer/training_args.py
  paddlenlp/transformers/llama/modeling.py
  paddlenlp/transformers/model_utils.py
Labels: contributor

#11115 [CI]Update loss
  scripts/distribute/ci_case_auto.sh
Labels: contributor
